### ISSUE TITLE
Is Sidekiq still not designed to work well with dozens of queues?

### ISSUE THREAD

**Issue by scottmartinnet** [mperham/sidekiq#2853] opened 2016-02-26 15:55 UTC
We want to separate our queues by customer so that each customer gets their own queue, unaffected by the processing of anyone else in the app.

But on https://github.com/mperham/sidekiq/wiki/Advanced-Options I see:
> Sidekiq is not designed to work well with dozens of queues.

Searching for this reveals this issue: https://github.com/mperham/sidekiq/issues/2388 which points to https://github.com/mperham/sidekiq/wiki/Reliability#watch-out, a paragraph that once described why many queues would result in performance issues, but which is no longer there.

Does this mean that this is no longer a real concern?  Or is there still a potential performance issue here?

**Comment by jonhyman** [comment] 2016-02-26 16:15
There still is a section there under Limitations. It reads:

> Redis does not provide a blocking reliable queue operation that works for multiple queues. This means that the Reliability feature needs to poll each queue. In practice that means if you have a lot of queues, your reliable Sidekiq processes will call Redis with up to (#queues * #processes) operations per second. If you have 100 queues and 5 processes, they can hit Redis up to 500 times per second! This is why I recommend you minimize the number of queues your application uses.

That is the performance issue, so as long as your Redis instance can handle the operations from Sidekiq, you can do what you want. Keep in mind that with many queues, you could also waste a lot of round-trips checking queues that are often empty.

**Comment by scottmartinnet** [comment] 2016-02-26 16:25
But if a worker is assigned to a particular queue, won't it only poll that queue?  Our workers will be dedicated to a single queue each.

**Comment by seuros** [comment] 2016-02-26 16:29
That correct. Workers will poll to only the queues assigned to.

**Comment by scottmartinnet** [comment] 2016-02-26 16:31
Beautiful.  So, for the record, the performance problem with many queues is limited to the situations where you have many workers polling many queues.  If workers are dedicated to a single queue (or a limited number of queues), there is no performance issue.

**Closed** 2016-02-26 16:31 UTC

**Comment by mperham** [comment] 2016-02-26 16:33
The problem is only with reliable fetch and only when a process is assigned a lot of queues.  Using the standard fetcher OR assigning queues to individual processes (as you are doing) will fix the issue.
