### ISSUE TITLE
Missing jobs in batch 

### ISSUE THREAD

**Issue by Saicheg** [mperham/sidekiq#2474] opened 2015-08-04 18:41 UTC
As i described on gitter. I realized a feature which uses sidekiq batches under the hood. Everythere were pretty fine on development and test. But in production after i missed some jobs on the 1st worker launch. I mean COMPLETE missed. Can't find them anywhere, in queue, failures, process.

Here is screenshot of how it looks: https://yadi.sk/i/zjnHLByriGMWz
6 hours after after couple full sidekiq restarts it is still there: https://yadi.sk/i/MVr1C7gSiGf9h

My sidekiq config:

```
require 'sidekiq-pro'

raw_yaml = YAML.load(File.read(File.join(File.expand_path('../../config/redis.yml', "config/redis.yml"))))
env = ENV['RAILS_ENV'] || 'development'
redis_config = raw_yaml[env]

sidekiq_config = YAML.load(File.read(File.join(File.expand_path('../../config/sidekiq.yml', "config/sidekiq.yml"))))

Sidekiq.configure_server do |config|
  config.reliable_fetch!
  config.reliable_scheduler!

  config.redis = {
      url: "redis://#{redis_config['host']}:#{redis_config['port']}/",
      namespace: 'sidekiq_clickcast'
  }
  ActiveRecord::Base.configurations[env]['pool'] = sidekiq_config[:concurrency].to_i + 2
  ActiveRecord::Base.establish_connection
end

Sidekiq.configure_client do |config|
  config.redis = {
      url: "redis://#{redis_config['host']}:#{redis_config['port']}/",
      namespace: 'sidekiq_clickcast'
  }
end

Sidekiq::Client.reliable_push! if env == 'staging' || env == 'production'
```

Gems:
```
gem 'sidekiq', '~> 3.4.2'
gem 'sidekiq-client-cli', '~> 0.1.7'
gem 'sidekiq-failures', github: 'mhfs/sidekiq-failures'                                                                                                       gem 'sidekiq-unique-jobs', '~> 3.0.2'
gem 'sidekiq-limit_fetch', '~> 2.2.6'
source <STRIPPED> do
  gem 'sidekiq-pro'             
end 
```

I can't reproduce it anymore. All other launches went fine.

**Comment by mperham** [comment] 2015-08-04 22:58
I can't explain it and you say you can't reproduce it anymore so what can we do?

**Comment by Saicheg** [comment] 2015-08-05 07:24
let's wait for couple days, and if issue will appear again - i will try to prepare something for you to reproduce. if not - we will mark it as incident.

**Comment by paulfri** [comment] 2015-08-05 17:00
I'm consistently seeing the same issue (my batch sizes are much larger, though). Roughly 1 in 3 batches are failing to complete successfully, and the missing jobs don't appear anywhere -- not in queues, retries, or dead pool. I'll gladly help debug if you have any ideas where to start.

![screen shot 2015-08-05 at 9 59 41 am](https://cloud.githubusercontent.com/assets/1364469/9092078/b48501b8-3b58-11e5-90d0-a1bba7ce109a.png)

**Comment by mperham** [comment] 2015-08-05 17:06
Are you using reliable fetch and/or autoscaling?  It's possible the jobs are stuck in the private per-process queues if the process doesn't restart.

**Comment by paulfri** [comment] 2015-08-05 17:11
I turned on reliable fetch prior to the most recent batch, and the issue persisted.

**Comment by mperham** [comment] 2015-08-05 17:22
I know that @jonhyman runs batches with hundreds of thousands or even millions of jobs in them.  He tracked down a number of job loss bugs years ago but l know of no job loss issues in the last year.  What 3rd party sidekiq extension gems are you running?  for instance, unique jobs can cause jobs to be registered with the batch but then never actually pushed to redis.

**Comment by paulfri** [comment] 2015-08-05 17:44
I'm not using any extensions, just `sidekiq` and `sidekiq-pro`.

Potentially weird behaviors that I can think of are:

1. New sets of jobs get pushed to the in-process batch dozens of thousands of times. There aren't any child batches, however.
2. The batches tend to have a lot of failures initially, due to connection pool timeouts (both ActiveRecord and a simple httparty-based API client, for rate limiting). These get sorted out pretty quickly via retries as the initial seed of jobs dies down and other, non-resource-constrained jobs start running.

**Comment by Saicheg** [comment] 2015-08-05 19:21
@paulfri glad to know that i am not alone :)

i can confirm that issue continues. new screenshot:

https://yadi.sk/i/0omrAlGAiHtuT

what i found that besides configuration in initializer, i have in my `unicorn.rb` file:

```
after_fork do |server, worker|
  defined?(ActiveRecord::Base) and
    ActiveRecord::Base.establish_connection

  # if preload_app is true, then you may also want to check and
  # restart any other shared sockets/descriptors such as Memcached,
  # and Redis.  TokyoCabinet file handles are safe to reuse
  # between any number of forked children (assuming your kernel
  # correctly implements pread()/pwrite() system calls)
  Sidekiq.configure_client do |config|
    raw_yaml = YAML.load(File.read(File.join(Rails.root, "config/redis.yml")))
    REDIS_CONFIG = raw_yaml[Rails.env]

    config.redis = {
      url: "redis://#{REDIS_CONFIG['host']}:#{REDIS_CONFIG['port']}/",
      :namespace => 'sidekiq_app_name'
    }
  end
end
```

can this affect reliable push somehow?

**Comment by distil-brewmaster** [comment] 2015-08-06 14:20
Could this be related to an issue I'm seeing where the on_success callback is firing before all jobs for the batch are complete?  

I created a batch of around 15 jobs and hooked an on_success callback up to cleanup behind them.  On a pretty frequent basis I am getting errors from one of the workers that it can't find resources that should be there.. the only reason the workers would be missing is if the on_success cleanup job ran first.

**Comment by mperham** [comment] 2015-08-06 17:22
Is everyone using the latest Sidekiq Pro?  Versions would help here.  If you aren't on 2.x, please upgrade.

@distil-brewmaster Can you show log output showing a JID X associated with BID Y running after BID Y's callbacks?  We need more than anecdotes; almost always these problems are application bugs.

**Comment by Saicheg** [comment] 2015-08-06 17:55
My `Gemfile.lock`

```
    sidekiq (3.4.2)
      celluloid (~> 0.16.0)
      connection_pool (~> 2.2, >= 2.2.0)
      json (~> 1.0)
      redis (~> 3.2, >= 3.2.1)
      redis-namespace (~> 1.5, >= 1.5.2)
    sidekiq-client-cli (0.1.7)
      cli
      sidekiq (>= 2.15)
    sidekiq-limit_fetch (2.2.6)
      sidekiq (>= 2.6.5, < 4.0)
    sidekiq-pro (2.0.7)
      sidekiq (>= 3.4.2)
```

**Comment by paulfri** [comment] 2015-08-06 18:04
```
    sidekiq (3.4.2)
      celluloid (~> 0.16.0)
      connection_pool (~> 2.2, >= 2.2.0)
      json (~> 1.0)
      redis (~> 3.2, >= 3.2.1)
      redis-namespace (~> 1.5, >= 1.5.2)
    sidekiq-pro (2.0.6)
      sidekiq (>= 3.4.2)
```

**Comment by Saicheg** [comment] 2015-08-11 20:21
an issue continues to appear! guys - any advices where i can dig and how i can try to reproduce it?

**Comment by mperham** [comment] 2015-08-11 20:51
@Saicheg Like any mysterious production problem, you'll need to instrument your system, collect metrics and narrow down where the problem appears.  I wrote this over a year ago about batches and it remains true today:

http://www.mikeperham.com/2014/05/27/the-reconciliation-step/

I will be happy to help with advice but only you can make the code changes and collect the data.

**Comment by pacoguzman** [comment] 2015-09-14 16:23
> Are you using reliable fetch and/or autoscaling? It's possible the jobs are stuck in the private per-process queues if the process doesn't restart.

In that case we're using both and we see we have a lot of inconsistencies and a lot of pending jobs in the internal queues that belonged to hosts that we're not going to start anymore. What do you suggest to deal with this problems in such scenarios?

**Comment by jonhyman** [comment] 2015-09-14 16:42
When we autoscale down, we first run a script which gracefully stops all the Sidekiq workers, and returns an error if they do not stop after the timeout period, and that aborts the auto-scale-down.

As for pending jobs in internal queues, we also wrote our own monitoring that does a `scan_each` with the pattern `queue:*_*_*` , saves everything it finds, and diffs every half hour to see if we have any jobs that are "stuck" (where stuck could be due to a frozen process or a machine that died that had jobs in an internal queue). We then manually reconcile, as it is an uncommon occurrence.

**Comment by pacoguzman** [comment] 2015-09-14 17:07
Thanks for the info.

If I understood it properly step one is not critical you can always
reconcile the jobs of those instances that didn't stop properly. Is that
right? Or I'm missing something.

By reconcile I'm thinking in moving to the corresponding queue, not the per
process queue, the jobs that still are on the process queues between
execution of the "script".

We thought on some expiration mechanism but that seems a lot easier and
probably less resource expensive.

Thanks again

**Comment by strukturedkaos** [comment] 2015-11-25 06:09
Has anyone found a the cause, solution or workaround to this pending jobs issue? I'm not using reliable fetch (yet) or performing any autoscaling, and I'm seeing plenty of batches seeming to be orphaned with pending jobs.

![image](https://cloud.githubusercontent.com/assets/528097/11389663/e8a592ae-9310-11e5-84b8-1cb9c2ac3a66.png)

@jonhyman - Would you be willing to share a gist of how you reconcile pending jobs?

**Comment by mperham** [comment] 2015-12-07 17:39
It is possible you have a unique jobs plugin which is cancelling the push to redis **after** the job is registered with the batch.  Sidekiq Enterprise's unique jobs feature specifically handles this case.

**Comment by strukturedkaos** [comment] 2015-12-07 18:55
@mperham - That is definitely a possibility. We are using ``sidekiq-unique-jobs`` to prevent duplicate jobs for queues that are not used by these batches. Could the batched jobs be affected even though I'm not using the plugin for them?

An update to my previous message, I was concerned that the pending jobs were caused by memory issues:

* Lowered concurrency from 15 to 10
* Decreased the number of servers from 10 to 5
* Moved Sidekiq to servers dedicated to running background workers (no web transactions)

After these changes, I haven't seen any pending jobs in the past 7 days. If I do see anymore pending jobs, I'll try removing the ``sidekiq-uniqueness-jobs`` gem.

Sidekiq Enterprise's features look great, but it's currently out of our price range as a startup.

**Comment by andersondias** [comment] 2015-12-08 19:03
@mperham same issue here.
I'm using sidekiq-ent 1.0.1, sidekiq-pro 3.0.0 and sidekiq 4.0.1. No sidekiq unique jobs plugin.

<img width="1200" alt="screenshot 2015-12-08 17 02 14" src="https://cloud.githubusercontent.com/assets/26751/11665244/7d9f06d0-9dcd-11e5-927f-dee1e98e9919.png">

**Comment by mperham** [comment] 2015-12-08 20:34
@andersondias What does your middleware chain look like?  Start Sidekiq with `-v` and it'll print it out.

**Comment by hicran** [comment] 2015-12-11 21:11
We keep running into the same issue:
![batch_pending_issue1](https://cloud.githubusercontent.com/assets/118728/11755481/5c06bc78-a018-11e5-8653-ab15c8ac90d4.png)
![batch_pending_issue2](https://cloud.githubusercontent.com/assets/118728/11755482/5c07c29e-a018-11e5-8d89-743395d8c390.png)

After re-starting there is -29 pending jobs:

```
2015-12-11T21:01:47.167Z 18192 TID-ovogqv4e0 DEBUG: ReliablePush activated
2015-12-11T21:01:47.167Z 18192 TID-ovogqv4e0 INFO: Booting Sidekiq 3.5.3 with redis options {:host=>"127.0.0.1", :port=>6379, :url=>nil}

                                   /\.                            /\
        L -      --- -- ---,,-.  ./.: 8.    .-----8p--.  .---.s,-'.:`--+
 ,8b  8i     ,F.oSSS"Sbo.o.s8 .\/.:'.oD \  /.:::.dS8b .\/ .: o8o ::::::|
 `4P,oP   ,o8;(88(`.:.4Y8 `"'::'.:."8DD:`\/ `:::.`888 :.db.::`P' `:'  `:
   o8P, .o8P   48bo.`:."`.dS`:'.oSSbDD8.`.oSSbo.`.888::oOOo oooo `.oSSbo o/
  d888Ld8P'  `:."88888o.``888 d88',`488 d8('.`88b:88( .8P'.:`888 d88P `88P
  88 8P8P     .`.:.`"Y88b 888 888 O 84P 888bod8P'.888o88 .:::888 88( O 888
 dP'`Y8P      db .:::.)8P 888 888 " 888b888'....: 888`.88b.::888 88b " 88(
T   ;88i      4P"888888P'o888o.Y8bod88P"`Y8bod8P d888b..488od888b V8bod888o
     88'                  48P::`odb.dSo,, ."P'.roy<sac>` ""'.`.o.`.."S"888.
     `8                    ".:'d888P'."S8b.`.::... ...' `.:::.d8b ::'  dP'
     .8                    `  '"888 ::.)88\odbo d8b`.odSso.::.888.::."488"
     .8                       `:888bod88P'.`888P"8Pd88'`488b::888::::.`8\
     P                        .:888 "P'..:::88(.:."88( O )88::48P::'/'/\ \
                             /\ 888`::./\`::888:::,888.".888::.o./\<:<  > >
 -   -  -- --- ------.  .---'  d888bo./  `-d888b.`:`Y8SbS8P'--48P'  \ \/ /
                      \/       `8P':/        "   \/   """      "     \/\/
                                P'\/                                    /<>\

2015-12-11T21:01:47.170Z 18192 TID-ovogqv4e0 INFO: Running in ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
2015-12-11T21:01:47.171Z 18192 TID-ovogqv4e0 INFO: Sidekiq Pro 2.1.3, commercially licensed.  Thanks for your support!
2015-12-11T21:01:47.171Z 18192 TID-ovogqv4e0 DEBUG: Middleware: Sidekiq::Middleware::Server::Logging, Sidekiq::Middleware::Server::RetryJobs, NewRelic::SidekiqInstrumentation, Sidekiq::Batch::Server
2015-12-11T21:01:47.171Z 18192 TID-ovogqv4e0 INFO: Starting processing, hit Ctrl-C to stop
2015-12-11T21:01:47.175Z 18192 TID-ovogv1yyk DEBUG: {:queues=>["default"], :labels=>["reliable"], :concurrency=>50, :require=>"./config/ports/background.rb", :environment=>nil, :timeout=>8, :poll_interval_average=>nil, :average_scheduled_poll_interval=>15, :error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x007fac6488e088>, #<Proc:0x007fac64f14b50@/.../.rvm/gems/ruby-2.2.2/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/sidekiq.rb:66>], :lifecycle_events=>{:startup=>[#<Proc:0x007fac64f4c3c0@/.../vendor/gems/sidekiq-pro/lib/sidekiq/shard_set.rb:70>], :quiet=>[], :shutdown=>[]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, :verbose=>true, :config_file=>"config/sidekiq.yml", :strict=>true, :backup_limit=>1000, :fetch=>Sidekiq::Pro::ReliableFetch, :index=>0}
2015-12-11T21:01:47.211Z 18192 TID-ovoh1h1sc INFO: ReliableFetch activated
2015-12-11T21:01:47.241Z 18192 TID-ovoh1h1sc WARN: ReliableFetch: recovering work on 34 messages
```
![batch_pending_issue3](https://cloud.githubusercontent.com/assets/118728/11755621/3de7ed38-a019-11e5-88ea-8e4575224164.png)

**Comment by mperham** [comment] 2015-12-11 21:24
@hicran Show me the output of `redis-cli info`.

**Comment by jschairb** [comment] 2015-12-11 21:34
@mperham Here's the information you requested from @hicran:

```
# Server
redis_version:3.0.4
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:b1907b950b5058eb
redis_mode:standalone
os:Linux 3.10.0-229.14.1.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.8.3
process_id:33372
run_id:991977bc6a068702a82145e451d3647118272351
tcp_port:6379
uptime_in_seconds:1924181
uptime_in_days:22
hz:10
lru_clock:7028908
config_file:/etc/redis.conf

# Clients
connected_clients:4
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:130534504
used_memory_human:124.49M
used_memory_rss:327753728
used_memory_peak:4150961456
used_memory_peak_human:3.87G
used_memory_lua:36864
mem_fragmentation_ratio:2.51
mem_allocator:jemalloc-3.6.0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1449869012
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:1
rdb_current_bgsave_time_sec:-1
aof_enabled:0                                                                                                                                                              [5/1965]
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:54816
total_commands_processed:20191575947
instantaneous_ops_per_sec:0
total_net_input_bytes:3473748444863
total_net_output_bytes:1075541379466
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:684
evicted_keys:2365
keyspace_hits:3001898207
keyspace_misses:2279795909
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:10085
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:222983.22
used_cpu_user:129067.16
used_cpu_sys_children:7896.41
used_cpu_user_children:62448.93

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=16898,expires=759,avg_ttl=7358648967
```

**Comment by mperham** [comment] 2015-12-11 21:37
Your middleware chain looks perfect and your Redis instance looks healthy.  I have no clue why you might be seeing invalid counts.  Is your batch code doing anything funky?

**Comment by hicran** [comment] 2015-12-11 22:18
```ruby
From Rake task:
batch = IndexMgmt::Helper::WorkerBatch.create_batch('TicketsWorker')
batch.jobs { IndexMgmt::Workers::TicketsWorker.perform_async }

module IndexMgmt::Workers
  class TicketsWorker

    include Sidekiq::Worker
    sidekiq_options retry: 5

  	def perform(offset = nil, params = {})
  	  offset, accounts = IndexMgmt::Account::Extract.fetch_from_destination(offset, params)
  	  accounts.each do |account|
        case account[:type]
          when "CLOUD"
            batch.jobs { enqueue_cloud_tickets_worker(account) }
          when "MANAGED_HOSTING"
              ...
         end
        end
  	  end

  	  unless accounts.empty?
  	    batch.jobs { self.class.perform_async(offset, params) }
  	  end
    end
    
    def enqueue_cloud_tickets_worker(cloud_account)
      IndexMgmt::Workers::CloudTicketsWorker.perform_async(cloud_account)
    end
  end
end

module IndexMgmt::Workers
  class CloudTicketsWorker
    include Sidekiq::Worker
    sidekiq_options retry: 5

    def perform(account)
      tickets = IndexMgmt::Cloud::Ticket::Extract.fetch(account[:number])

      tickets.each do |ticket|
        batch.jobs { enqueue_cloud_ticket_worker(ticket) }
      end
    end

    def enqueue_cloud_ticket_worker(cloud_ticket)
      IndexMgmt::Workers::CloudTicketWorker.perform_async(cloud_ticket)
    end
  end
end

module IndexMgmt::Workers
  class CloudTicketWorker
    include Sidekiq::Worker

    sidekiq_options retry: 5

    def load_ticket(ticket)
      IndexMgmt::Cloud::Ticket::Load.load_ticket(ticket)
    end

    def perform(ticket)
      load_ticket(ticket)
    end
  end
end
```

**Comment by mperham** [comment] 2015-12-12 16:48
Code looks great.  Run this in your production Rails console:

Sidekiq.client_middleware.map(&:klass).join(', ')

**Comment by hicran** [comment] 2015-12-12 19:05
[1] index_mgmt(main)> Sidekiq.client_middleware.map(&:klass).join(', ')
=> "Sidekiq::Batch::Client"

**Comment by mperham** [comment] 2015-12-12 20:49
Ok, I can't explain why batch is flaky for you.  Everything looks optimal.

If you are seeing pending > 0, that would indicate jobs which were registered with the batch but never actually made it into Redis.  If you are seeing pending < 0, that would indicate duplicate job execution.

**Comment by hicran** [comment] 2015-12-14 15:09
Could this be related to what @jschairb mentioned here: https://github.com/mperham/sidekiq/issues/2201#issuecomment-162718449

Our application does not use redis directly, all of our workers are written the same way I had pasted here.

**Comment by mperham** [comment] 2015-12-14 17:05
@hicran I don't know if it is related.  The info output above shows 4 connected clients.

**Comment by hicran** [comment] 2015-12-14 17:14
I think we are running the application in 4 containers. I don't have access to production environment configurations yet. @jschairb might be able to help us with that better.

**Comment by allcentury** [comment] 2016-02-16 22:16
We're also seeing the same behavior and having a hard time tracking down the root cause:

![screenshot 2016-02-16 17 10 52](https://cloud.githubusercontent.com/assets/5561166/13092890/5acf563e-d4d0-11e5-9387-0450e574a6b2.png)

To add even more confusion, we run this batch every 30 minutes but have these jobs expire every 25 minutes to avoid duplication:

```ruby
class MyWorker
  include Sidekiq::Worker

  sidekiq_options retry: 3,
                  queue: :my_worker_queue,
                  expires_in: 25.minutes

```

I don't really get how a batch that's 3hrs old can show a job as 'pending' when all of those should have either failed/succeeded or expired.

Versions and details:

```ruby
Sidekiq.client_middleware.map(&:klass).join(', ')
=> "Sidekiq::Middleware::Client::Batch, Sidekiq::Middleware::Expiry::Client"
```

```ruby
sidekiq (4.1.0)
      concurrent-ruby (~> 1.0)
      connection_pool (~> 2.2, >= 2.2.0)
      redis (~> 3.2, >= 3.2.1)
    sidekiq-pro (3.0.5)
      sidekiq (>= 4.0.0)
```

Let me know if there's anything else I can provide.

**Comment by mperham** [comment] 2016-02-16 22:18
Show me your server middleware (printed on server startup with -v).

**Comment by allcentury** [comment] 2016-02-16 22:42
Added the server middleware above.

**Comment by mperham** [comment] 2016-02-16 22:47
@allcentury Your expiry/batch middleware looks good, expired jobs should be counted as successful and not sit at pending forever.  Are you reopening these batches to add jobs anywhere?

**Comment by allcentury** [comment] 2016-02-16 22:54
No we're not reopening the batch.

**Comment by mperham** [comment] 2016-02-16 23:39
You can use `Sidekiq::Batch.new(bid).jids` to get the remaining JIDs and then grep your logs to see if there's any common or unexpected behavior associated with those JIDs.  Are you invalidating jobs ever?

**Comment by mperham** [comment] 2016-04-14 20:40
One way you can get "extra" jobs in a batch is if you add jobs to a batch after it is defined.  You are only allowed to add jobs to a batch at two points:

1. Within the first `jobs` block when the batch is first created.
2. Within a job which is part of the batch's job set.

For instance, this is illegal and can cause errors since it is racy:

```ruby
b = Sidekiq::Batch.new
# ok
b.jobs do
  SomeWorker.perform_async
end

# bad bad bad, can't add more jobs here
b.jobs do
  AnotherWorker.perform_async
end
```

You also cannot add jobs to a batch within a callback for that batch but you **can** add jobs to a parent batch within the callback for a child batch.  If your counts are off, make sure you are following these rules.

**Comment by mperham** [comment] 2016-06-22 23:35
I don't want to hold open issues for months or years without any progress or solution.  Please comment here or open a new issue if you find more data.

**Closed by mperham** 2016-06-22 23:35 UTC
Labels: pro

**Comment by myfitment** [comment] 2016-06-28 15:38
Same issue. I have a particular batch I'm running that loads files. Kicks off a batch job for each line, runs critical processing in ```on_complete``` at the very end.

I just did ```flushall``` in redis in our production environment and restarted Sidekiq. I attempted to run this  batch for a file with only 4 lines in it:

![image](https://cloud.githubusercontent.com/assets/2339454/16421534/43acbf4e-3d23-11e6-9561-bd778957d58a.png)

```Redis``` info is:

    # Server
    redis_version:2.8.13
    redis_git_sha1:00000000
    redis_git_dirty:0
    redis_build_id:bde26fe75260d2ed
    redis_mode:standalone
    os:Linux 3.4.109-amazon-xen x86_64
    arch_bits:64
    multiplexing_api:epoll
    gcc_version:4.5.4
    process_id:14546
    run_id:1b7b9f4a5d296af2a5ef6ee4e107ddd66a17d486
    tcp_port:6379
    uptime_in_seconds:49419
    uptime_in_days:0
    hz:10
    lru_clock:7509898
    config_file:/etc/redis_util.conf

    # Clients
    connected_clients:135
    client_longest_output_list:0
    client_biggest_input_buf:0
    blocked_clients:0

    # Memory
    used_memory:5856928
    used_memory_human:5.59M
    used_memory_rss:6303744
    used_memory_peak:612340664
    used_memory_peak_human:583.97M
    used_memory_lua:43008
    mem_fragmentation_ratio:1.08
    mem_allocator:jemalloc-3.2.0

    # Persistence
    loading:0
    rdb_changes_since_last_save:2023900
    rdb_bgsave_in_progress:0
    rdb_last_save_time:1467078271
    rdb_last_bgsave_status:ok
    rdb_last_bgsave_time_sec:-1
    rdb_current_bgsave_time_sec:-1
    aof_enabled:1
    aof_rewrite_in_progress:0
    aof_rewrite_scheduled:0
    aof_last_rewrite_time_sec:0
    aof_current_rewrite_time_sec:-1
    aof_last_bgrewrite_status:ok
    aof_last_write_status:ok
    aof_current_size:54512843
    aof_base_size:168689
    aof_pending_rewrite:0
    aof_buffer_length:0
    aof_rewrite_buffer_length:0
    aof_pending_bio_fsync:0
    aof_delayed_fsync:1

    # Stats
    total_connections_received:1066
    total_commands_processed:5714999
    instantaneous_ops_per_sec:281
    rejected_connections:0
    sync_full:0
    sync_partial_ok:0
    sync_partial_err:0
    expired_keys:77
    evicted_keys:0
    keyspace_hits:316365
    keyspace_misses:1116891
    pubsub_channels:0
    pubsub_patterns:4
    latest_fork_usec:6554

    # Replication
    role:master
    connected_slaves:0
    master_repl_offset:0
    repl_backlog_active:0
    repl_backlog_size:1048576
    repl_backlog_first_byte_offset:0
    repl_backlog_histlen:0

    # CPU
    used_cpu_sys:170.38
    used_cpu_user:76.87
    used_cpu_sys_children:3.13
    used_cpu_user_children:0.40

    # Keyspace
    db0:keys=29,expires=21,avg_ttl=4297628551

Gems:

    redis-3.3.0
    sidekiq-4.1.2
    sidekiq-ent-1.2.1
    sidekiq-4.1.2
    sidekiq-pro-3.2.1

The *only* other Sidekiq gem I have running is one that runs a Chef recipe at EngineYard. Has nothing to do with operations.

My business depends on this job running, because these files are so complex as to take at least 36 hours to run in linear fashion. Running a large one with Sidekiq takes only about 20 minutes.

Here's my class method that runs the batch:

    def process_all_rows_text(upload_id)

      upload = Upload.find(upload_id)
      if File.exists?(upload.local_file_name)
        filename = upload.local_file_name
      else
        filename = upload.download.to_s
      end
      header = nil
      col_sep = ","
      col_sep = "\t" if filename.downcase.ends_with?(".txt")

      batch = Sidekiq::Batch.new
      batch.on(:complete, self, 'upload_id' => upload.id)
      batch.jobs do
        IO.foreach(filename) do |line|
          if header.blank?
            header = CSV.parse_line(line.encode!('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '').strip, col_sep: col_sep)
            next
          end
          if col_sep=="\t"
            vals = line.encode!('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '').strip.split(col_sep)
          else
            vals = CSV.parse_line(line.encode!('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '').strip, col_sep: col_sep)
          end

          VipReader.perform_async(upload_id, vals, row_number)
        end
      end
    end

Code is pretty straightforward. Willing to do anything to get the batch running reliably, including updating Redis.

**Comment by mperham** [comment] 2016-06-28 15:44
Adrian, can you give me access to the myfitment code and I'll give it a code review?  I can't think of why a Batch with 4 jobs would be consistently failing.

**Comment by myfitment** [comment] 2016-06-28 15:51
It’s not failing consistently with only 4. I just ran it again and it ran through. It failed after that restart though, when the system was pretty pristine. I can’t figure out where the pending jobs go when they neither run nor fail. That’s a pretty old version of redis, could that be it? I did add you as a collaborator. The file is lib/classes/vip_reader.rb. The actual job itself is pretty complex and is due for a refactoring, but it’s mostly a procedural loading of data that requires some processing before it’s persisted.




Adrian Klingel
(919) 740-4478

PO Box 487
Wake Forest, NC 27588
Adrian.Klingel@myfitment.com <mailto:Adrian.Klingel@illumaware.com>
http://www.myfitment.com

-- 









This transmission is for the sole use of the intended recipient(s) and may contain information that is confidential and/or privileged. If you are not the intended recipient, please delete this transmission and any attachments and notify the sender by return email immediately. Any unauthorized review, use, disclosure or distribution is prohibited.

**Comment by mperham** [comment] 2016-06-28 15:53
Version of Redis should not matter, as long as you are using a supported version which you are.

**Comment by mperham** [comment] 2016-06-28 16:01
Is that the only batch type that is regularly giving you problems or do you see it with all types of batches?

**Comment by myfitment** [comment] 2016-06-28 16:15
I see it with others, but I have not documented which ones. I am keeping a log starting now.




Adrian Klingel
(919) 740-4478

PO Box 487
Wake Forest, NC 27588
Adrian.Klingel@myfitment.com <mailto:Adrian.Klingel@illumaware.com>
http://www.myfitment.com

-- 









This transmission is for the sole use of the intended recipient(s) and may contain information that is confidential and/or privileged. If you are not the intended recipient, please delete this transmission and any attachments and notify the sender by return email immediately. Any unauthorized review, use, disclosure or distribution is prohibited.

**Comment by mperham** [comment] 2016-06-28 16:36
I think one major issue in your system is you're performing ad hoc rescues and logging the error messages into logfiles or the database, saving backtraces to Redis, etc.  Are you still using BugSnag?  I would rip out all rescues and `backtrace: true` from your Sidekiq jobs and config and simply rely on BugSnag.

If you do this, you'll get a nice dashboard for seeing all errors in your system; now you can tackle those issues one at a time.  The problem today is there's no easy visibility as to which of your jobs are failing within a batch and why.

**Comment by myfitment** [comment] 2016-06-28 16:41
I have a check_file method that checks the actual data, so I probably should be removing these rescues.



Adrian Klingel
(919) 740-4478

PO Box 487
Wake Forest, NC 27588
Adrian.Klingel@myfitment.com <mailto:Adrian.Klingel@illumaware.com>
http://www.myfitment.com

-- 









This transmission is for the sole use of the intended recipient(s) and may contain information that is confidential and/or privileged. If you are not the intended recipient, please delete this transmission and any attachments and notify the sender by return email immediately. Any unauthorized review, use, disclosure or distribution is prohibited.

**Comment by mperham** [comment] 2016-06-28 16:48
The only thing I can think of is a malformed job.  It looks like you are doing a lot of CSV and XLSX processing - I can imagine a scenario where a line contains non-UTF8 content.  Ruby somehow creates a JSON blob for that job with an argument that contains badly encoded data.  I noticed you are not using reliable_fetch or timed_fetch so when Sidekiq pops that job off a queue, it would try to parse the JSON, which would throw an exception (since the job data in Redis is not valid UTF8 JSON) and the job would be lost, never to be performed and the batch would stay pending forever.

So first thing I would do: enable timed_fetch.

```ruby
Sidekiq.configure_server do |config|
  config.timed_fetch!
end
```

All that said, do you see error messages involving file or string encoding errors?

**Comment by myfitment** [comment] 2016-06-28 17:52
I frequently get string encoding errors. I have many many Pacific region customers, primarily China and Taiwan. The files contain invisible (and sometimes visible) characters all the time.




Adrian Klingel
(919) 740-4478

PO Box 487
Wake Forest, NC 27588
Adrian.Klingel@myfitment.com <mailto:Adrian.Klingel@illumaware.com>
http://www.myfitment.com

-- 









This transmission is for the sole use of the intended recipient(s) and may contain information that is confidential and/or privileged. If you are not the intended recipient, please delete this transmission and any attachments and notify the sender by return email immediately. Any unauthorized review, use, disclosure or distribution is prohibited.

**Comment by myfitment** [comment] 2016-06-28 18:14
I added that setting.




Adrian Klingel
(919) 740-4478

PO Box 487
Wake Forest, NC 27588
Adrian.Klingel@myfitment.com <mailto:Adrian.Klingel@illumaware.com>
http://www.myfitment.com

-- 









This transmission is for the sole use of the intended recipient(s) and may contain information that is confidential and/or privileged. If you are not the intended recipient, please delete this transmission and any attachments and notify the sender by return email immediately. Any unauthorized review, use, disclosure or distribution is prohibited.

**Comment by mperham** [comment] 2016-06-28 18:32
I suspect that's likely the source of your problem.  If you dig into the batches that failed and look at the source input data, I'd bet you'd find it to be non-English data.  You need to use a tool like `iconv` or something similar to convert all input into UTF8 or strip out non-UTF8 characters.

That's a general rule for **all** user input: massage all input data into a known format/encoding (typically UTF8) and don't trust the sender.

**Comment by myfitment** [comment] 2016-06-29 00:42
Thanks Mike. 




Adrian Klingel
(919) 740-4478

PO Box 487
Wake Forest, NC 27588
Adrian.Klingel@myfitment.com <mailto:Adrian.Klingel@illumaware.com>
http://www.myfitment.com

-- 









This transmission is for the sole use of the intended recipient(s) and may contain information that is confidential and/or privileged. If you are not the intended recipient, please delete this transmission and any attachments and notify the sender by return email immediately. Any unauthorized review, use, disclosure or distribution is prohibited.

**Comment by mlarraz** [comment] 2016-06-29 12:07
Having a similar issue here.

We have daily job that simply creates a batch containing around 100k independent jobs. Of these there is usually one persistent failure. However, when this happens there are always 60-70 jobs stuck pending the next day.

We've started scheduling a second, backup job an hour after the first one, to enqueue any remaining work to be done. It works, but this is exactly the solution we had before switching to Sidekiq Pro, and replacing it with batches and automatic retries was one of the main reasons we wanted to switch.

**Comment by mperham** [comment] 2016-06-29 15:30
@mlarraz Would you open your own issue and give us a more info about your setup, versions, initializer, etc?  I'm especially interested in any errors the system generates while processing the batch jobs.
