### ISSUE TITLE
Sidekiq 3.3.2 + pro 2.0.0 - redis connections growing indefinitely

### ISSUE THREAD

**Issue by webandtech** [mperham/sidekiq#2201] opened 2015-02-24 01:55 UTC
Upgrading to Sidekiq 3.3.2 plus Sidekiq Pro 2.0.0 (with associated configuration changes) caused us to reach our redis connection limit of 255 within a few minutes (typically we see 30 or fewer). This happened even with Sidekiq sitting idle with no jobs being enqueued.

I did not attempt to troubleshoot it, but a downgrade fixed the problem immediately.

**Comment by mperham** [comment] 2015-02-24 01:57
Can you give me a gem version diff?

**Comment by webandtech** [comment] 2015-02-24 02:02
This is from my commit to revert the change:

````
#Gemfile.lock
-    sidekiq (3.3.2)
+    sidekiq (3.3.0)
-      connection_pool (>= 2.1.1)
+      connection_pool (>= 2.0.0)
-    sidekiq-pro (2.0.0)
-      sidekiq (>= 3.3.2)
+    sidekiq-pro (1.9.2)
+      sidekiq (>= 3.2.3)
-  sidekiq-pro
+  sidekiq (= 3.3.0)
+  sidekiq-pro (= 1.9.2)

````

**Comment by ryansch** [comment] 2015-02-24 05:20
Mike: This sounds a lot like the problem I had.  I fixed it by monkey patching connection_pool.  I have extremely limited availability right now but feel free to mention me and I'll see what I can do.

**Comment by mperham** [comment] 2015-02-24 23:36
This is almost certainly due to a recent change in connection_pool 2.1.1. https://github.com/mperham/connection_pool/pull/67 Your Redis connections are being discarded for some reason.

@ryansch Can you share your solution or link to your original issue?

**Comment by aprescott** [comment] 2015-02-25 00:35
Two apps at work are encountering this same problem. I don't know if it's from #2195 though.

**Comment by aprescott** [comment] 2015-02-25 01:01
> Two apps

Make that 3.

**Comment by mperham** [comment] 2015-02-25 01:03
Can anyone share a small app that reproduces the behavior?

**Comment by aprescott** [comment] 2015-02-25 14:26
I can try to carve out time to get a minimal reproduction, but can I ask what the ramifications are of maxing out the available Redis connections? 2 of the 3 apps I've seen facing this issue could revert the Pro 2.0 upgrade because they weren't using batches, but the other does use batches so I can't easily just revert. I seem to have not hit any errors yet, but if/when it happens, what situation would people seeing this bug be facing? Does it prevent enqueuing jobs from the client web nodes?

**Comment by mperham** [comment] 2015-02-25 19:20
Try connection_pool master: https://github.com/mperham/connection_pool/pull/67#issuecomment-76034734

**Comment by mperham** [comment] 2015-02-25 19:33
Ugh, seriously Redis client? https://github.com/redis/redis-rb/issues/516

**Comment by seangeo** [comment] 2015-02-27 02:10
I've been hit by this issue too, upgrading to connection_pool master didn't seem to resolve it.

``
  * sidekiq (3.3.2)
  * sidekiq-pro (1.9.2)
``

Concurrency is 4, redis connection pool sizes are the default: 5. One worker and one web process on heroku. Using RedisToGo mini with 50 connections. 

The problem occurs when there a sidekiq workers that create other sidekiq jobs using perform_async. For example, I have a CSV upload worker that splits the file into rows, then starts a worker for each row, those workers then parse the row, inserts something in the database and creates a couple other workers to send emails or call APIs. So if I upload a csv file with 20 or so rows, about 100 jobs or so should be scheduled. This is fine but as soon as the second lot of workers start creating their own child workers, the redid connection count shoots straight to 50 and I start getting max connection errors. 

What's particularly annoying is that it seems to prevent batch callbacks from being triggered as well.

**Comment by mperham** [comment] 2015-02-27 03:34
You've got to upgrade to Redis 3.2.1 also.

**Comment by mperham** [comment] 2015-03-02 21:04
Any news?  Does redis 3.2.1 + connection_pool master work better?

**Comment by seangeo** [comment] 2015-03-02 21:13
Ah sorry, I meant to reply here. Yes it does. The problem is solved with redis 3.2.1 and connection_pool master. Thanks!!

**Comment by mperham** [comment] 2015-03-02 21:22
Thank you so much.  connection_pool 2.1.2 has been released with the fix.

**Closed by mperham** 2015-03-02 21:22 UTC

**Comment by aprescott** [comment] 2015-03-03 20:27
Can confirm the connection_pool update to 2.1.2 (with redis-rb 3.2.1) seems to resolve the problems.

**Comment by webandtech** [comment] 2015-03-03 20:31
Works for me as well. Thanks all!

**Comment by AvonGenesis** [comment] 2015-04-10 20:53
I currently have this problem. Sidekiq 3.3.3, Sidekiq-pro 2.0.1, connection_pool 2.1.3, with redis-rb 3.2.1 Sitting at 572 idle connections over the course of 18 days with 2 workers at 50 concurrency each.

**Comment by mperham** [comment] 2015-04-10 21:33
I'm working on a series of gem releases which will revert connection pool behavior back to 2.1.0 and fix unnecessary Redis connection thrashing in Sidekiq Pro.

**Comment by jschairb** [comment] 2015-12-08 00:51
Are there any more updates to this? Our application had 3300+ redis connections before we started investigating further. We're more aggressively killing idle connections now since the default behavior in Redis is to leave them open indefinitely.

Sidekiq 3.5.3, Sidekiq-pro 2.1.3, connection_pool 2.2.0, redis-rb 3.2.1, and redis 3.0.4.

Also of interest to some: http://redis.io/topics/clients#client-timeouts

```By default recent versions of Redis don't close the connection with the client if the client is idle for many seconds: the connection will remain open forever.
However if you don't like this behavior, you can configure a timeout, so that if the client is idle for more than the specified number of seconds, the client connection will be closed.```

**Comment by mperham** [comment] 2015-12-08 00:55
@jschairb That's likely a connection leak somewhere in your application.  Use the `id` support to determine whose connection is leaking. https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#322
