### ISSUE TITLE
Scheduled job loss - possible explanations?

### ISSUE THREAD

**Issue by ttrmw** [mperham/sidekiq#4275] opened 2019-09-17 14:28 UTC
Ruby version: 2.4.1
Sidekiq / Pro / Enterprise version(s): Sidekiq Pro 4.0.2

Initializer:

```
if AppConfig.fetch(:redis, nil)                                                   
  Sidekiq.configure_server do |config|                                            
    config.redis = {                                                              
      url: AppConfig[:redis].fetch(:url, nil),                                    
      password: AppConfig[:redis].fetch(:auth, nil)                               
    }                                                                             
  end                                                                             
                                                                                  
  Sidekiq.configure_client do |config|                                            
    config.redis = {                                                              
      url: AppConfig[:redis].fetch(:url, nil),                                    
      password: AppConfig[:redis].fetch(:auth, nil)                               
    }                                                                             
  end                                                                             
end                                                                               
                                                                                  
Sidekiq.configure_client do |config|                                              
  config.client_middleware do |chain|                                             
    chain.add Middleware::RecordJob                                               
  end                                                                             
end                                                                               
                                                                                  
# The jobs running in the Sidekiq server can themselves push new jobs to Sidekiq, thus acting as clients.
# So we add the RecordJob middleware on the server too                            
Sidekiq.configure_server do |config|                                              
  config.client_middleware do |chain|                                             
    chain.add Middleware::RecordJob                                               
  end                                                                             
  config.server_middleware do |chain|                                             
    chain.add Middleware::SetJobStartTime                                         
    chain.add Middleware::CancelDuplicateJobs                                     
    chain.add Middleware::RejectCancelledJob                                      
  end                                                                             
end   
```

Hey! We have just introduced a second application server, on which the majority of our Sidekiq processes now run. Since making this change, we're starting to lose a significant number of scheduled jobs.

Our setup records jids into our database at schedule time, and touches the record at start time (the `RecordJob` middleware referenced in the initializer).

What we're seeing is the jobs in question are scheduled, but never started. We do not see them in the sidekiq logs at all, and the affected jids do not appear to be in Redis.

Concurrently with this, we are seeing significant latency and quite a few Redis timeouts. The Redis instance remains on the original app server, so the majority of our worker processes are talking to a Redis instance over the network via stunnel. 

I observe that the docs state here:

"Sidekiq's default scheduler is not atomic, it pops jobs off the scheduled queue and enqueues them with two network round trips. Sidekiq Pro offers a reliable scheduler which uses Lua to perform the same task atomically"

I believe due to our middleware usage it'd be impractical to enable reliable_scheduler, though I'm willing to consider it if there's no better option.

However, I'm wondering if this is likely to be the explanation. The relevant job has quite low volume at the moment, maybe 3 or 4 every five minutes or so for the past few days. I'm seeing about 40s between the logs showing a timeout and the next job processing, so the likelihood of us being stung by the issue quoted above seems exceedingly low to me, and I'm not sure where else we should be looking.

**Comment by mperham** [comment] 2019-09-17 15:59
I would start at the lowest level: Redis.  Determine the cause of those Redis timeouts and everything using it should work much better: nothing can be built on a foundation of sand. Review the Using Redis wiki page and review your production metrics for issues.

https://github.com/mperham/sidekiq/wiki/Using-Redis
http://www.mikeperham.com/2017/04/20/monitoring-redis/

**Comment by ttrmw** [comment] 2019-11-26 12:53
Hey @mperham can we reopen? 

We've resolved our Redis timeouts and are still seeing the issue. We know that our client side middleware is hit - this records the jid into our db. Our first server side middleware sets a start time, and this doesn't succeed when we lose the job.

Where should we look next? I'm going to add a gratuitous amount of logging to see how far we get, as this doesn't seem to be reproduceable in dev...

**Comment by ttrmw** [comment] 2019-11-26 13:21
If relevant, the jobs in question always form part of a batch, causing the batches to stick in pending. The JIDs appear in the batch in the web panel.

**Comment by mperham** [comment] 2019-11-26 22:26
The issue doesn't trigger any ideas on my side so let us know if you make any progress with that logging output.  I will close this if I don't hear back in a few weeks.

**Comment by ttrmw** [comment] 2019-11-30 12:50
Ha. I was rather hoping you might have some suggestions for me!

My logging didn't really show a great deal. Our client side middleware is hit, none of the server side middleware runs. This is pretty much what I was expecting I think. So the flow appears to be that the job schedules (although I can't actually prove that as I've never personally witnessed a job appear in the sidekiq web panel/scheduled set that later disappeared like this), is recorded by our client middleware in the db, then disappears before entering the queue.

If I 'cheat' in dev and nil out the job before the Client#push call in Sidekiq's schedule.rb, I see identical behaviour - recorded jid, disappearing job, client middleware at schedule time and no server side middleware. But it seems to me to be pretty unlikely (correct me if I'm wrong tho, I don't know too much about redis!) that this would happen exactly per my contrived cheaty test.

We're not currently using reliable scheduler, super fetch or reliable push. The former presents a bit of a refactoring problem for us as we currently lean on client side middleware. 

I'm certain you'll advise us to enable these features, and I most likely will, but if doing so would fix our issue can you point me at some symptoms I might be able to see that would prove it? If my cheaty test scenario depicts the behaviour that the scheduler atomicity problem creates accurately, fair, that seems a good bet, but I would have assumed you'd see some kind of exception rather than nil job value - any pointers there?

**Comment by mperham** [comment] 2019-11-30 13:57
﻿
Are you using a unique jobs plugin? That’ll stop jobs.

**Comment by ttrmw** [comment] 2019-12-02 14:12
We are not, no. We have a hand rolled solution that prevents duplication of some jobs for some contexts, but we're losing jobs that do not utilise this so can rule it out with reasonable confidence.

**Comment by mperham** [comment] 2020-03-25 17:42
Closing as stale. I hope you found some conclusion here.

**Closed by mperham** 2020-03-25 17:42 UTC

**Comment by ttrmw** [comment] 2020-03-30 20:18
fair enough. Not really, but thanks anyway.

**Comment by mperham** [comment] 2020-03-30 20:19
I would suggest you upgrade.  Bugs get fixed all the time; you weren't clear on which version of Sidekiq you are running.

**Comment by carlows** [comment] 2020-08-20 19:46
It might not have anything to do with your issue, but one thing to consider is whether your sidekiq job is being processed by a worker in an unexpected instance.

For example, I've had a situation where I was running some sidekiq workers in two different places (Beanstalk and Kubernetes) and they both used the same Redis instance. One of them wasn't properly configured and it silently failed. So when the faulty instance picks the sidekiq job, it looks like your job was not executed because you don't see it in any logs where you'd expect it.

So, that is one possible reason why you might see that the scheduled jobs get lost. Hope it saves some time to someone in the future 🙂.
