### ISSUE TITLE
Sidekiq stop doing his jobs after new deployment on Heroku 

### ISSUE THREAD

**Issue by 01010000101001100** [mperham/sidekiq#2869] opened 2016-03-04 14:05 UTC
Hello.

My background workers works just fine till the moment I push new code to Heroku - after that they are unresponsive. There is no jobs in the queue, all has been done but the new jobs don't trigger. The funny part is - I can see Sidekiq running in idle mode.

Here is log from heroku when you deploy new code:
```
source=sidekiq.1 dyno=heroku.47293156.bada71bf-f0ff-4f1c-8eed-c7528a4590b6 sample#memory_total=99.87MB sample#memory_rss=99.54MB sample#memory_cache=0.33MB sample#memory_swap=0.00MB sample#memory_pgpgin=30401pages sample#memory_pgpgout=4835pages
2016-03-04T13:39:46.513742+00:00 app[sidekiq.1]: 3 TID-oqxe2rlt4 WARN: Terminating 2 busy worker threads
2016-03-04T13:39:46.590552+00:00 app[sidekiq.1]: 3 TID-oqxe2rlt4 WARN: Work still in progress [#<struct Sidekiq::BasicFetch::UnitOfWork queue="queue:default", job="{\"class\":\"TwitterStreamWorker\",\"args\":[\"2351093755-uLQNoPMfoKGopRsCs6ikJAW2egUtoQCkloJfZUK\",\"ZRpX7aDvD7KnnF7u4tG3BkTjU00Z7sZnPTB6Yo4cRXfVg\",2],\"retry\":true,\"queue\":\"default\",\"jid\":\"29b3c3f599cb9f3eddadc317\",\"created_at\":1457096875.3749962,\"enqueued_at\":1457096875.3751173}">, #<struct Sidekiq::BasicFetch::UnitOfWork queue="queue:default", job="{\"class\":\"TwitterStreamWorker\",\"args\":[\"2990004218-KY9nFfjniczRS1a6VlnlRRFKBMVZ0aXRb0pxKie\",\"KYAztMy5OuFEkVd0zmYDbnbOSg8JCYoFV49GY1oSM5ccT\",1],\"retry\":true,\"queue\":\"default\",\"jid\":\"f42038fc90ba7eae62a94efd\",\"created_at\":1457027345.788974,\"enqueued_at\":1457048830.3125458,\"error_message\":\"end of file reached\",\"error_class\":\"EOFError\",\"failed_at\":1457047735.858541,\"retry_count\":3,\"retried_at\":1457048725.594568}">]
2016-03-04T13:39:46.590593+00:00 app[sidekiq.1]: 3 TID-oqxe2rlt4 DEBUG: Re-queueing terminated jobs
2016-03-04T13:39:48.163683+00:00 heroku[sidekiq.1]: Error R12 (Exit timeout) -> At least one process failed to exit within 10 seconds of SIGTERM
2016-03-04T13:39:48.163858+00:00 heroku[sidekiq.1]: Stopping remaining processes with SIGKILL
2016-03-04T13:39:50.259397+00:00 heroku[sidekiq.1]: Process exited with status 137

```

**Comment by mperham** [comment] 2016-03-04 16:37
Dupe of #2866?

Error R12 indicates your Redis might be too slow.  You should lower the timeout with `-t 5` or so.

**Comment by mperham** [comment] 2016-03-04 17:49
Try 4.1.1

**Closed by mperham** 2016-03-04 17:49 UTC

**Comment by 01010000101001100** [comment] 2016-03-05 10:54
@mperham more logs. I noticed this weird **:error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x007fe7a5d2c370>**


```
2016-03-05T10:47:06.694787+00:00 heroku[sidekiq.1]: Restarting
2016-03-05T10:47:06.695537+00:00 heroku[sidekiq.1]: State changed from up to starting
2016-03-05T10:47:06.730595+00:00 heroku[web.1]: State changed from up to starting
2016-03-05T10:47:06.729837+00:00 heroku[web.1]: Restarting
2016-03-05T10:47:09.071730+00:00 heroku[sidekiq.1]: Starting process with command `bundle exec sidekiq -c 3 -v -t 5 -e production`
2016-03-05T10:47:09.190032+00:00 heroku[web.1]: Starting process with command `bundle exec puma -C config/puma.rb`
2016-03-05T10:47:09.692260+00:00 heroku[sidekiq.1]: State changed from starting to up
2016-03-05T10:47:10.399000+00:00 heroku[sidekiq.1]: Stopping all processes with SIGTERM
2016-03-05T10:47:11.198737+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2016-03-05T10:47:11.528793+00:00 app[sidekiq.1]: 3 TID-org0tf19o DEBUG: Got TERM signal
2016-03-05T10:47:11.529435+00:00 app[sidekiq.1]: 3 TID-org0tf19o INFO: Shutting down
2016-03-05T10:47:11.530373+00:00 app[sidekiq.1]: 3 TID-org1an3yw INFO: Scheduler exiting...
2016-03-05T10:47:11.529849+00:00 app[sidekiq.1]: 3 TID-org0tf19o INFO: Terminating quiet workers
2016-03-05T10:47:12.033291+00:00 app[sidekiq.1]: 3 TID-org0tf19o INFO: Pausing to allow workers to finish...
2016-03-05T10:47:12.094784+00:00 app[web.1]: [3] Puma starting in cluster mode...
2016-03-05T10:47:12.094806+00:00 app[web.1]: [3] * Version 2.14.0 (ruby 2.3.0-p0), codename: Fuchsia Friday
2016-03-05T10:47:12.094807+00:00 app[web.1]: [3] * Min threads: 5, max threads: 5
2016-03-05T10:47:12.094823+00:00 app[web.1]: [3] * Environment: production
2016-03-05T10:47:12.094825+00:00 app[web.1]: [3] * Process workers: 2
2016-03-05T10:47:12.094826+00:00 app[web.1]: [3] * Preloading application
2016-03-05T10:47:12.287110+00:00 app[web.1]: [3] - Gracefully shutting down workers...
2016-03-05T10:47:12.515599+00:00 app[web.1]: [3] === puma shutdown: 2016-03-05 18:47:12 +0800 ===
2016-03-05T10:47:12.515648+00:00 app[web.1]: [3] - Goodbye!
2016-03-05T10:47:13.543403+00:00 app[sidekiq.1]: 3 TID-org0tf19o INFO: Bye!
2016-03-05T10:47:13.603966+00:00 heroku[web.1]: Process exited with status 0
2016-03-05T10:47:13.637967+00:00 app[sidekiq.1]: 3 TID-oxaxdk0mk INFO: Running in ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
2016-03-05T10:47:13.637998+00:00 app[sidekiq.1]: 3 TID-oxaxdk0mk INFO: See LICENSE and the LGPL-3.0 for licensing details.
2016-03-05T10:47:13.676233+00:00 app[sidekiq.1]: 3 TID-oxaxdk0mk DEBUG: Client Middleware:
2016-03-05T10:47:13.637999+00:00 app[sidekiq.1]: 3 TID-oxaxdk0mk INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2016-03-05T10:47:13.638210+00:00 app[sidekiq.1]: 3 TID-oxaxdk0mk INFO: Booting Sidekiq 4.1.1 with redis options {:url=>"redis://redistogo:REDACTED@chubb.redistogo.com:9875/"}
2016-03-05T10:47:13.679018+00:00 app[sidekiq.1]: 3 TID-oxaxdk0mk DEBUG: Server Middleware: Sidekiq::Middleware::Server::Logging, Sidekiq::Middleware::Server::RetryJobs, Sidekiq::Middleware::Server::ActiveRecord
2016-03-05T10:47:13.682161+00:00 app[sidekiq.1]: 3 TID-oxaxdk0mk DEBUG: {:queues=>["default"], :labels=>[], :concurrency=>3, :require=>".", :environment=>"production", :timeout=>5, :poll_interval_average=>nil, :average_scheduled_poll_interval=>15, :error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x007fe7a5d2c370>], :lifecycle_events=>{:startup=>[], :quiet=>[], :shutdown=>[]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, :verbose=>true, :strict=>true, :tag=>"app"}
2016-03-05T10:47:13.679042+00:00 app[sidekiq.1]: 3 TID-oxaxdk0mk INFO: Starting processing, hit Ctrl-C to stop
2016-03-05T10:47:14.540874+00:00 heroku[sidekiq.1]: Process exited with status 0
2016-03-05T10:47:15.851084+00:00 app[web.1]: [3] * Listening on tcp://0.0.0.0:23194
```

**Comment by mperham** [comment] 2016-03-05 16:38
That looks totally normal.  I don't know what you mean by "weird".
