### ISSUE TITLE
Sidekiq::Batch::Callback no implicit conversion of nil into String

### ISSUE THREAD

**Issue by jhoffner** [mperham/sidekiq#2541] opened 2015-09-07 21:10 UTC
I’m having some issues with the batch functionality with Sidekiq Pro and wanted to see if I could get some perspective from you on what the issue might be. 

There are two issues. 

1. Sidekiq::Batch::Callback is constantly failing
2. Sidekiq batches are showing invalid date information

I’ve tracked this down to line 251 of batch.rb:

`@callbacks = Sidekiq.load_json(props['callbacks'.freeze])`

The issue is that a callback was not provided, so there are no callbacks. `props[‘callbacks’]` returns nil.

**Comment by jonhyman** [comment] 2015-09-07 21:16
Do you ever call a jobs block? If you look at the code, callbacks should
never be nil. If no callbacks are provided it'll be an empty array.

Sent from my mobile device

I’m having some issues with the batch functionality with Sidekiq Pro and
wanted to see if I could get some perspective from you on what the issue
might be.

There are two issues.

   1. Sidekiq::Batch::Callback is constantly failing
   2. Sidekiq batches are showing invalid date information

I’ve tracked this down to line 251 of batch.rb:

@callbacks = Sidekiq.load_json(props['callbacks'.freeze])

The issue is that a callback was not provided, so there are no callbacks.
props[‘callbacks’] returns nil.

—
Reply to this email directly or view it on GitHub
<https://github.com/mperham/sidekiq/issues/2541>.

**Comment by jonhyman** [comment] 2015-09-07 21:17
I mean empty hash.

**Comment by jhoffner** [comment] 2015-09-07 22:51
Unless I've missed something I never create a job without actually using it (call the jobs block). I'm assuming even if I did though, wouldnt the batch instance just never get used for anything?

The batch failures that I am getting have active batch ids within Sidekiq.

**Comment by ryansch** [comment] 2015-09-07 22:57
What versions of sidekiq and sidekiq-pro are you running?  Any other sidekiq plugins?

**Comment by jhoffner** [comment] 2015-09-07 22:58
```
    sidekiq (3.5.0)
      celluloid (~> 0.17.0)
      connection_pool (~> 2.2, >= 2.2.0)
      json (~> 1.0)
      redis (~> 3.2, >= 3.2.1)
      redis-namespace (~> 1.5, >= 1.5.2)
    sidekiq-failures (0.4.5)
      sidekiq (>= 2.16.0)
    sidekiq-pro (2.0.8)
      sidekiq (>= 3.4.2)
    sidekiq-statistic (1.1.0)
      sidekiq (~> 3.3, >= 3.3.4)
    sidekiq-unique-jobs (3.0.15)
      sidekiq (>= 2.6)
```

**Comment by ryansch** [comment] 2015-09-07 23:03
What does your batch instantiation look like?

**Comment by jhoffner** [comment] 2015-09-07 23:14
So thats the one thing thats a little special, I had started to write a simple batchable concern so that I could track batches for specific root models during a request/thread lifecycle. 

```ruby
module Batchable
  extend ActiveSupport::Concern

  def sidekiq_batch_id(key = :default)
    @sidekiq_batch_ids ||= {}
    @sidekiq_batch_ids[key] ||= "sidekiq_batch_#{self.class.name}_#{id}_#{key}"
  end

  # Will re-use or create a new batch specific for this model instance.
  # You can optionally inherit the active batch instead, if there is one, by setting inherit to true
  # You can pass in a key value to have different batches for the same model
  def sidekiq_batch(key: :default, inherit: false)
    (inherit ? Thread.current[:sidekiq_batch] : nil) || Thread.current[sidekiq_batch_id(key)] ||= Sidekiq::Batch.new.tap do |batch|
      batch.description = "#{self.class.name}: #{id} - #{key}"
      batch.on(:success, BatchLoggerCallback)
      batch.on(:complete, BatchLoggerCallback)
    end
  end

end
```

then 

```ruby
candidate.sidekiq_batch.jobs do
      positions.each do |position|
        Candidate::DetermineMatchWorker.perform_async(candidate.id.to_s, position.id.to_s)
      end
    end
```
*NOTE* I just added the callback events, which do work for the expeted batches but I am still getting errors. 

It looks like the errors that I am getting are for batches that status show `@key=:"current-70151801229140">, @bid="Lm485jvdNvszMQ", @props={"pending"=>"0", "total"=>"1", "kids"=>"0"}, @failures=0, @completed=0` which is interesting. Total == 1 but failures and completed == 0, yet its trying to fun the batch callback.

**Comment by jhoffner** [comment] 2015-09-07 23:17
Also I've got this situation happening in my UI. Notice the Start time. If I click on the link I get a failed page with the same error as reported. 

![_staging__sidekiq_pro](https://cloud.githubusercontent.com/assets/579835/9723686/fe4f5108-557b-11e5-9629-efd99017a67a.png)

**Comment by mperham** [comment] 2015-09-08 16:50
Same issue as #2268.

**Comment by mperham** [comment] 2015-09-08 16:51
There's a failure case I'm not handling but I don't know what it is yet: Redis evicting batch data due to memory constraints?  Networking issues causing data corruption?  Can you paste your `redis-cli info` output?

**Comment by jhoffner** [comment] 2015-09-08 17:02
Definitely not memory constraint issues. I am using the compose.io service in production but I've seen this issue on my local as well. 

My local output

```
# Server
redis_version:2.8.19
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:3255dfb4c3511ec0
redis_mode:standalone
os:Linux 3.13.0-40-generic x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.7.2
process_id:1
run_id:c515d5eb850732f2e5079965148536f5fc39ba54
tcp_port:6379
uptime_in_seconds:400947
uptime_in_days:4
hz:10
lru_clock:15667895
config_file:

# Clients
connected_clients:11
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:1

# Memory
used_memory:3608416
used_memory_human:3.44M
used_memory_rss:1216512
used_memory_peak:4110880
used_memory_peak_human:3.92M
used_memory_lua:37888
mem_fragmentation_ratio:0.34
mem_allocator:jemalloc-3.6.0

# Persistence
loading:0
rdb_changes_since_last_save:87
rdb_bgsave_in_progress:0
rdb_last_save_time:1441731111
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:694
total_commands_processed:166670
instantaneous_ops_per_sec:0
total_net_input_bytes:30330876
total_net_output_bytes:5207892
instantaneous_input_kbps:0.19
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:307
evicted_keys:0
keyspace_hits:24546
keyspace_misses:2902
pubsub_channels:0
pubsub_patterns:1
latest_fork_usec:409

# Replication
role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:215.16
used_cpu_user:186.05
used_cpu_sys_children:5.54
used_cpu_user_children:4.05

# Keyspace
db0:keys=147,expires=110,avg_ttl=148915323982
db2:keys=3,expires=0,avg_ttl=0
```

**Comment by GermanDZ** [comment] 2015-10-06 16:01
I'm suffering the same problem. Seems to be related to #2474. Missing jobs in batches could lead to "pendings counter" going to negative and going to positive again.

Are callbacks invoked each time the pendings counter reach zero?

**Comment by mperham** [comment] 2015-10-06 16:06
@GermanDZ Nope, callbacks are guaranteed only to fire once as Sidekiq Pro tracks which ones have been triggered.

**Comment by GermanDZ** [comment] 2015-10-06 16:13
My Rollbar is polluted with a few hundred of those every week. Somehow the batch information is removed but the batch remains "live", the callback fails trying to parse an empty hash. The Pro UI doesn't fail but clearly can't show information from a empty hash.

![image](https://cloud.githubusercontent.com/assets/570991/10314514/80ac5a16-6c55-11e5-9993-43cc29389bf7.png)

![image](https://cloud.githubusercontent.com/assets/570991/10314528/932052d8-6c55-11e5-93a2-76008973cb83.png)

**Comment by ggilder** [comment] 2015-11-06 19:29
Hi, I'm seeing the same thing with callback jobs failing on `TypeError: no implicit conversion of nil into String`. I don't actually have any batch callbacks registered, fwiw. I also have the problem with the Batches UI showing batches from "46 years ago", and attempting to load the batch detail page results in a 500 because the same `TypeError` is raised. My redis server is not configured to do any automatic eviction.

Any update on this issue?

**Comment by mperham** [comment] 2015-11-06 20:23
@ggilder I'd love to fix it but no one, including myself, can reproduce the problem.  :-(  We need to understand why the batch data is disappearing.

**Comment by ggilder** [comment] 2015-11-06 21:34
Is there anything I can do to help diagnose? If you give me some pointers about where to look I can certainly post some details.

**Comment by GermanDZ** [comment] 2015-11-06 21:52
A clue: "some jobs are adding more jobs to the same batch"

The condition to made callback is `failed == pendings`. But when the last
job adds a new job, the condition is true multiple times for the same batch.

**Comment by mperham** [comment] 2015-11-06 22:50
@GermanDZ That should not be the case.  Sidekiq Pro tracks if it has fired the complete callback and will not issue redundant callbacks.

**Comment by GermanDZ** [comment] 2015-11-07 07:09
I know, I've read the code but not debugged it. But that is what I've
observe every day.

**Comment by mperham** [comment] 2015-11-07 16:56
@GermanDZ I'm not sure I have a test which verifies my claim that so I will write one next week and see if that reproduces your finding.  Can you open an issue?

**Comment by sax** [comment] 2015-12-04 18:19
We're running into the same issue every few days, ever since updating Sidekiq (3.2.6 -> 4.0.1) and Pro (1.8.0 -> 2.1.1). Our redis version is 2.8.5. It is not memory constrained, and it is configured not to save.

This seems to only happen in one type of our worker, where workers in the batch will enqueue other jobs.

**Comment by jonhyman** [comment] 2015-12-04 18:26
@sax we've seen this happen with race conditions when we purposefully break the atomicity of `batch.jobs` -- basically the batch "completes" before another job is enqueued in that batch (granted, I think we have a fairly advanced use case). Is it possible for you, if you do not already have an `on_success` callback to create one, and to add logging in that callback saying that it ran for a certain `bid`. Then if you get this error, check your logs to see if the batch completed _before_ the error occurred. If that's the case, there's a race condition somewhere.

**Comment by sax** [comment] 2015-12-04 20:05
We have an `on_complete` callback already. Even looking at the logs for the last few days (just in case the errors are caused by very old jobs), I don't see any logs related to this batch...

**Comment by mperham** [comment] 2015-12-04 20:19
@sax Could you post a full backtrace and the code for the worker which is enqueuing other jobs?

**Comment by sax** [comment] 2015-12-04 22:35
The error is being thrown here, in our middleware that checks whether a batch has been invalidated. If a batch does not finish after a certain timeout, we call `#invalidate_all` on it from a cron job, and then use this to keep from doing unnecessary work when the jobs come up.

```
module Sidekiq
  module Middleware
    module Server
      class BatchValidator
        def call(worker, msg, queue)
          worker.bid = msg['bid']
          begin
            yield if worker.batch.nil? || worker.batch.valid?(msg['jid'])
          rescue Sidekiq::Batch::NoSuchBatch => e
            NewRelic::Agent.add_custom_parameters(worker_class: worker.class.name)
            NewRelic::Agent.notice_error e
          end
        end
      end
    end
  end
end
```

```
2015-12-04T09:32:17.818Z 38704 TID-b713s WARN: TypeError: no implicit conversion of nil into String
2015-12-04T09:32:17.818Z 38704 TID-az5jg WARN: /home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in `initialize'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in `new'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq.rb:141:in `load_json'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-pro-2.1.1/lib/sidekiq/batch.rb:280:in `load_data'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-pro-2.1.1/lib/sidekiq/batch.rb:62:in `initialize'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-pro-2.1.1/lib/sidekiq/pro/worker.rb:8:in `new'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-pro-2.1.1/lib/sidekiq/pro/worker.rb:8:in `batch'
/home/product-feeds/app/releases/20151202220817/lib/sidekiq/middleware/server/batch_validator.rb:8:in `call'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-pro-2.1.1/lib/sidekiq/batch/middleware.rb:26:in `call'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-unique-jobs-3.0.2/lib/sidekiq-unique-jobs/middleware/server/unique_jobs.rb:16:in `call'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/logging.rb:30:in `with_context'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:127:in `block in process'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:166:in `stats'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:126:in `process'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:79:in `process_one'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
/home/product-feeds/app/shared/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

There's quite a bit of code in the workers themselves that I don't feel comfortable putting an issue. Maybe I can email a link to a private gist?

**Comment by mperham** [comment] 2015-12-05 00:10
Email me a private gist is fine.  Note that you are using an invalid combination: Pro 2 is for Sidekiq 3.  You need to `bundle update sidekiq-pro` and get Pro 3.

**Comment by mperham** [comment] 2015-12-05 00:12
And you should use the `Sidekiq::Worker#valid_within_batch?` method as it is more efficient than what you are currently doing: https://github.com/mperham/sidekiq/wiki/Batches#canceling-a-batch

**Comment by mattcamuto** [comment] 2015-12-05 01:22
@mperham I work with @sax..

One other artifact I am seeing is that when this error occurs the sidekiq_retries_exhausted block was getting called multiple times for the same class/args. We are using uniq extension as well as an fyi. Not sure if this is related but just something observed.

````ruby
  sidekiq_options unique: true, retry: 3
````

We will update the sidekiq-pro version and monitor it.

**Comment by mperham** [comment] 2015-12-05 22:50
If it is possible, remove the unique extension and see if the batch error continues to appear.  I would also like to see the worker code that is manipulating the batch.

**Comment by sax** [comment] 2015-12-08 22:21
I realized looking closer at the code that our workers do not, in fact, add more jobs to the batch. I misunderstood what they were doing (as I said, it's a lot of code).

Fixing our middleware to use the newer `Sidekiq::Worker#valid_within_batch?` solves the current error point... If it was because of a batch we had previously invalidated, then that will solve the core problem.

One other thing of note, in case it adds more light to the situation, or is useful to you. Our batches get large enough that we can't use atomic push... we were consuming way too much memory when we tried. Instead, we use the following code to keep the batch open long enough for all jobs to be enqueued:

```ruby
module Sidekiq
  class NonatomicBatch < Batch

    class BufferWorker
      include Sidekiq::Worker
      sidekiq_options queue: :lifecycle

      def perform(bid, feed_activity_id, state)
        Sidekiq.logger.info "Buffer job running for batch #{bid}, feed_activity_id: #{feed_activity_id}"
      end
    end

    attr_reader :buffer_job_uid

    def initialize(bid: nil, feed_activity: nil)
      @feed_activity = feed_activity
      super(bid)
    end

    def jobs(buffer_delay = 1.hour)
      # Grab the current batch in case this jobs call is nested
      original_batch = Thread.current[:sidekiq_batch]

      Sidekiq.logger.info "BufferWorker about to enqueue jobs for batch #{bid}, feed_activity_id: #{@feed_activity.id}"

      # Execute the original batch logic. This will use the built-in atomic_push, but with a job scheduled in the future.
      # After the batch is "finished" and the atomic_push puts the buffer work in redis, we can add all of the real jobs
      # using our own yield.
      # Calling super will nil out Thread.current[:sidekiq_batch] before it returns
      super() do
        # Enqueue a delayed job at the beginning of batch, to ensure the batch is alive
        # for the buffer_delay amount of time even if queue is empty before then
        @buffer_job_uid = BufferWorker.perform_in(buffer_delay, bid, @feed_activity.id, @feed_activity.state)
      end

      # Setting Thread.current[:sidekiq_batch] ensures that Sidekiq::Client.push will
      # push jobs into the current batch anywhere inside the yielded block.
      Thread.current[:sidekiq_batch] = self

      # Queue jobs slowly (or quickly), but non-atomically
      yield

      # Reschedule the buffer job to run immediately. This has to happen outside
      # of the batch context, or the batch will think it has one more job than
      # it really does, and never actually complete.
      Thread.current[:sidekiq_batch] = nil
      run_buffer_worker!

      # Return jobs that have been added to this batch, like the parent class
      @added
    ensure
      # Unlike Sidekiq::Batch, we set the original job back afterwards
      Thread.current[:sidekiq_batch] = original_batch
    end

    def run_buffer_worker!
      Sidekiq.logger.info "BufferWorker about to run buffer job for batch #{bid}, feed_activity_id: #{@feed_activity.id} job id #{buffer_job_uid}"
      buffer = Sidekiq::ScheduledSet.new.find_job(buffer_job_uid)
      buffer.add_to_queue if buffer
    end
  end
end
```

**Comment by mperham** [comment] 2015-12-08 23:53
@sax I would be very careful with that code, you're treading on thin ice depending on implementation details.  If you wish to parallelize batch creation, you should create initial meta-jobs in the batch which themselves create a subset of the actual jobs atomically.

**Comment by mperham** [comment] 2015-12-08 23:56
e.g. if you want to create a batch with one million jobs, create 100 meta-jobs, each of which add 10,000 jobs to the batch.

**Comment by sax** [comment] 2015-12-09 00:09
Yeah, upgrades are scary :smile: 

We're not really working on parallel batch creation, but on balancing resource utilization while avoiding the race condition of batch enqueuing vs batch processing. Our batches used to close in mid-enqueuing.

One of our problems is that we don't necessarily know how big a batch is until it finishes enqueuing. For instance, in one part of this application we stream process large files into batches. For a 2G XML file, it would be prohibitively expensive for us to calculate the total number of line items in the file. We want to keep as little of the data in memory as possible.

**Comment by mperham** [comment] 2015-12-09 00:17
Got it, rock > you < hard place.  Stream processing is not easy to parallelize.

It's entirely possible that this error is caused by the non-atomic impl, it's really hard to say one way or another.

**Comment by jonhyman** [comment] 2015-12-09 00:24
@sax fwiw we do something similar, it's part of what causes us to break the atomicity (though it's one reason of many, but RAM definitely is a consideration). Instead of subclassing to your extent, we just use private APIs to register a fake jid in the batch and then mark it as being successful. It's hacky, but IMO less so than your solution which enqueues a bogus job (that has to be found and removed, and `find_job(jid)` is very slow as `zcard` gets very large) and manually manipulating `Thread.current[:sidekiq_batch]` yourself.

**Comment by sax** [comment] 2015-12-09 00:35
@jonhyman ahah. Yeah, that might be a better solution for us. This could very well be causing our problem. Is your code in a sharable state? If not, I'll see if I can make something with less monkeying.

**Comment by kbacha** [comment] 2016-02-08 19:52
Ok, I may have figured out how to "reproduce" this issue. It appears to happen if a batch "succeeds" and then has more added to it.

Here's the code that does it:

```ruby
 class TestCapacity                                     
   include Sidekiq::Worker                              
                                                        
   sidekiq_options retry: false                         
                                                        
   def perform(number_of_jobs)                          
     batch = Sidekiq::Batch.new                         
     batch.on(:success, self.class)                     
     batch.on(:complete, self.class)
     batch.jobs do
       Generics::DummyBatch.perform_in(1.seconds, {})
     end
 
     sleep 30
     
     number_of_jobs.to_i.times do |n|
       sleep 0.1
       batch.jobs do
         Generics::DummyBatch.perform_in(1.seconds, {})
       end
     end
   end
   
   def on_success(*args)
     puts 'yay!'
   end
   
   def on_complete(*args)
     puts 'completed!'
   end
 end
                                                       
```

The "DummyBatch" is just a no-op. Essentially, the first job finishes but we still have reference to the batch and we start adding to it again.

This causes the batch to get "broken" and results in the batch saying it's from the unix epoch. Let me know if this helps you guys figure it out.

**Comment by mperham** [comment] 2016-02-08 21:09
@kbacha Sadly, that is expected behavior.  Once you have defined a batch's first `jobs` block, the system is asynchronous and you cannot edit it further externally without facing race conditions.  The only way to safely add jobs to a batch is from within a job in that batch.  Otherwise you need to handle the case where the batch is finished, i.e. gone.  For instance, you could set a custom flag for the bid in Redis in a success callback which lives for 1 day, allowing any external logic know that the batch is done and gone.

**Comment by kbacha** [comment] 2016-02-08 21:12
@mperham Yea, I understand that it's expected behavior, I'm backing out the code that was resulting in these races.

I just thought I would point it out since it causes this exact error. Basically, we get the implicit type conversion error, and the batches are older than 46 years, and clicking on the batch results in a 500.

Maybe we should only let you call `batch.jobs` once? And after that the batch is completely immutable?

**Comment by kbacha** [comment] 2016-02-08 21:21
@mperham I suppose the only thing it needs to do is to throw an exception if you initialize with a bid but that bid doesn't exist. Would that work?

**Comment by jonhyman** [comment] 2016-02-08 21:54
The way we do this is that when we break the atomicity on purpose, we use private APIs to register a fake jid, then add_success when we're done enqueueing the jobs, but it is still prone to something like a machine crashing and the batch never completing.

If you initialize a bid that doesn't exist, it will already raise an exception.

**Comment by mperham** [comment] 2016-02-08 21:56
Since this is likely a cause of this issue and we've never found any other cause, I'm going to close this.

**Closed by mperham** 2016-02-08 21:56 UTC
