### ISSUE TITLE
ThreadError: can't alloc thread

### ISSUE THREAD

**Issue by benoittgt** [mperham/sidekiq#4029] opened 2018-11-28 15:05 UTC
Ruby version:
- sidekiq-pro (4.0.2)
- sidekiq (5.1.3)

```
13:29:02.713804+00:00 app worker_notifications.1 - - 4 TID-1u06zw SendNotificationsWorker JID-754eb57d86009b5a6baee320 INFO: SidekiqMemorySampling queue=notifications worker=SendNotificationsWorker jid=754eb57d86009b5a6baee320 
13:29:02.719922+00:00 app worker_notifications.1 - - 4 TID-1u06no SendNotificationsWorker JID-fdd856cc57c54585cd4aab19 INFO: SidekiqMemorySampling queue=notifications worker=SendNotificationsWorker jid=fdd856cc57c54585cd4aab19 
13:29:02.727448+00:00 app worker_notifications.1 - - 4 TID-1u06zw WARN: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context
13:29:02.727736+00:00 app worker_notifications.1 - - 4 TID-1u06zw WARN: {"context":"processor"}
13:29:02.727917+00:00 app worker_notifications.1 - - 4 TID-1u06zw WARN: ThreadError: can't alloc thread
13:29:02.728000+00:00 app worker_notifications.1 - - 4 TID-1u06zw WARN: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:23:in `new'
13:29:02.728003+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:23:in `safe_thread'
13:29:02.728004+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:65:in `start'
13:29:02.728005+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:96:in `block in processor_died'
13:29:02.728007+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:91:in `synchronize'
13:29:02.728008+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:91:in `processor_died'
13:29:02.728009+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:79:in `rescue in run'
13:29:02.728010+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:70:in `run'
13:29:02.728012+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
13:29:02.728013+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
13:29:02.728151+00:00 app worker_notifications.1 - - W, [2018-11-28T13:29:02.728053 #4] WARN -- : **Airbrake: falling back to sync delivery because there are no running async workers
13:29:02.728239+00:00 app worker_notifications.1 - - 4 TID-1u06zw ERROR: !!! ERROR HANDLER THREW AN ERROR !!!
13:29:02.728289+00:00 app worker_notifications.1 - - 4 TID-1u06zw ERROR: attempted to build can't alloc thread with closed Airbrake instance
13:29:02.728369+00:00 app worker_notifications.1 - - 4 TID-1u06zw ERROR: /app/vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-2.10.0/lib/airbrake-ruby/notifier.rb:59:in `build_notice'
13:29:02.728371+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-2.10.0/lib/airbrake-ruby/notifier.rb:117:in `send_notice'
13:29:02.728372+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-2.10.0/lib/airbrake-ruby/notifier.rb:43:in `notify'
13:29:02.728374+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-2.10.0/lib/airbrake-ruby.rb:199:in `notify'
13:29:02.728375+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/airbrake-7.3.3/lib/airbrake/sidekiq.rb:19:in `notify_airbrake'
13:29:02.728377+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/exception_handler.rb:20:in `call'
13:29:02.728378+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/exception_handler.rb:20:in `block in handle_exception'
13:29:02.728379+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/exception_handler.rb:18:in `each'
13:29:02.728380+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/exception_handler.rb:18:in `handle_exception'
13:29:02.728382+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:18:in `rescue in watchdog'
13:29:02.728383+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:15:in `watchdog'
13:29:02.728384+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
13:29:02.729120+00:00 app worker_notifications.1 - - #<Thread:0x000000000d374ad0@/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:23 aborting> terminated with exception (report_on_exception is true):
28 Nov 2018 14:29:02.991225 <190>1 2018-11-28T13:29:02.729212+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:23:in `new': can't alloc thread (ThreadError)
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:23:in `safe_thread'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:65:in `start'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:96:in `block in processor_died'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:91:in `synchronize'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:91:in `processor_died'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:79:in `rescue in run'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:70:in `run'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

I found this comment https://github.com/mperham/sidekiq/issues/2732#issuecomment-166706814 but we don't have complicated custom initializer with Redis. For the moment I am not able to find where this could happen. When we go on `/app/vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-2.10.0/lib/airbrake-ruby/notifier.rb:59:in `build_notice'` https://github.com/airbrake/airbrake-ruby/blob/v2.10.0/lib/airbrake-ruby/notifier.rb#L59 we only raise an error.

We don't have a peak of threads or memory in NewRelic. 
![screenshot 2018-11-28 at 15 58 40](https://user-images.githubusercontent.com/8417720/49160299-c5f0ce80-f326-11e8-974c-8e648400f251.png)

![screenshot 2018-11-28 at 16 04 13](https://user-images.githubusercontent.com/8417720/49160562-5202f600-f327-11e8-88f0-36cbd42e4b58.png)

We are on a standard-2x Heroku dyno with 512 threads available.

```ruby
require 'sidekiq'

Sidekiq.configure_client do |config|
  config.redis = { url: ***, size: (ENV['SIDEKIQ_REDIS_CLIENT_SIZE'] || 1) }
  config.error_handlers << proc { |ex, ctx_hash| Airbrake.notify(ex, ctx_hash) }
end

Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq::Extensions.enable_delay!

Sidekiq.logger.level = Logger::WARN if Rails.env.test?

Sidekiq.configure_server do |config|
  config.super_fetch!
  config.reliable_scheduler!
  config.server_middleware do |chain|
    chain.add Sidekiq::MemorySamplingMiddleware
    chain.add Sidekiq::RetryMonitoringMiddleware
    chain.add Sidekiq::ExceptionMonitoringMiddleware
  end
end
```

Do you have any ideas?

**Comment by mperham** [comment] 2018-11-28 20:41
Wow, there is a LOT happening in that log output, fours errors by my count:


```
ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context
```

The root problem, this is a known issue with Sidekiq Pro, I have no idea of the cause.

```
ThreadError: can't alloc thread
```

Another occasional problem I see in issue reports.  I believe this is an OS limit or glibc issue but the error is too vague to narrow down.

```
**Airbrake: falling back to sync delivery because there are no running async workers
```

I haven't used Airbrake in many years so I can't help here.

```
attempted to build can't alloc thread with closed Airbrake instance
```

Perhaps this process was shutting down, which shutdown Airbrake but too early?

**Comment by mperham** [comment] 2018-11-28 20:44
What version of Redis and the redis gem?

**Comment by benoittgt** [comment] 2018-11-28 20:53
Thanks Mike for your answer.

We are trying to reproduce the issue in a small app but this is not easy. We will share it if we can.

For Redis gem (4.0.2) and Redis instance (on Redis Cloud) 4.0.10.

**Comment by benoittgt** [comment] 2018-11-28 21:44
Here is more logs because I think previous issue with [`net-http2`](https://github.com/ostinelli/net-http2) (we use threw [apnotic](https://github.com/ostinelli/apnotic) could lead to this

```
21:00:28.948269+00:00 app worker_notifications.1 - - 4 TID-1vmpzc NotifyUsersWorker JID-2ad585ace725f61ee5c96f1c INFO: start
21:00:29.130949+00:00 app worker_notifications.1 - - 4 TID-1vmpzc NotifyUsersWorker JID-2ad585ace725f61ee5c96f1c INFO: done: 0.172 sec
21:00:29.138196+00:00 app worker_notifications.1 - - 4 TID-1vmpg4 SendNotificationsWorker JID-b9a9bbf6aa3988e75ecf370e INFO: start
21:00:29.616835+00:00 app worker_notifications.1 - - 4 TID-1vmozs NotifyUsersWorker JID-58346489888b5b649dbecea9 INFO: start
21:00:29.801498+00:00 app worker_notifications.1 - - 4 TID-1vmozs NotifyUsersWorker JID-58346489888b5b649dbecea9 INFO: done: 0.185 sec
21:00:29.804085+00:00 app worker_notifications.1 - - 4 TID-1vmoss SendNotificationsWorker JID-46c08dc0512a5ad79e8194a3 INFO: start
21:00:30.013912+00:00 app worker_notifications.1 - - 4 TID-1vmpg4 SendNotificationsWorker JID-b9a9bbf6aa3988e75ecf370e INFO: done: 0.883 sec
21:00:30.318281+00:00 app worker_notifications.1 - - 4 TID-1vmq5o NotifyUsersWorker JID-66a07d41826499f21aab9f34 INFO: start
21:00:30.557814+00:00 app worker_notifications.1 - - 4 TID-1vmq5o NotifyUsersWorker JID-66a07d41826499f21aab9f34 INFO: done: 0.239 sec
21:00:30.559547+00:00 app worker_notifications.1 - - 4 TID-1vmpn4 SendNotificationsWorker JID-6ad5ad861633016e2c083f05 INFO: start
21:00:30.562378+00:00 app worker_notifications.1 - - W, [2018-11-28T21:00:30.562296 #4]  WARN -- : [APN] Could not process notification 83089816: {"reason"=>"Unregistered", "timestamp"=>1536843049341} | status: 410 | headers: {":status"=>"410", "apns-id"=>"************************************"}
21:00:30.690472+00:00 app worker_notifications.1 - - 4 TID-1vmoss SendNotificationsWorker JID-46c08dc0512a5ad79e8194a3 INFO: done: 0.886 sec
21:00:31.118295+00:00 app worker_notifications.1 - - 4 TID-1vmom4 NotifyUsersWorker JID-8b43afb592dacfcba4bc0684 INFO: done: 0.214 sec
21:00:31.119657+00:00 app worker_notifications.1 - - 4 TID-1vmp9g SendNotificationsWorker JID-b7896781ff2d3dce531a3ef8 INFO: start
21:00:31.712420+00:00 app worker_notifications.1 - - 4 TID-1vmptg NotifyUsersWorker JID-1dd52efb71952dacd90f4f73 INFO: start
21:00:32.041502+00:00 app worker_notifications.1 - - 4 TID-1vmptg NotifyUsersWorker JID-1dd52efb71952dacd90f4f73 INFO: done: 0.329 sec
21:00:32.125062+00:00 app worker_notifications.1 - - 4 TID-1vmpn4 SendNotificationsWorker JID-6ad5ad861633016e2c083f05 INFO: done: 1.575 sec
21:00:32.665480+00:00 app worker_notifications.1 - - W, [2018-11-28T21:00:32.665324 #4]  WARN -- : [APN] Could not process notification 83089826: {"reason"=>"Unregistered", "timestamp"=>1543431934288} | status: 410 | headers: {":status"=>"410", "apns-id"=>"************************************"}
21:00:32.703168+00:00 app worker_notifications.1 - - 4 TID-1vmp9g SendNotificationsWorker JID-b7896781ff2d3dce531a3ef8 INFO: done: 1.583 sec
21:00:47.542020+00:00 app worker_notifications.1 - - 4 TID-1vmp9g NotifyUsersWorker JID-fa80fdc7a83fee777d4bfbce INFO: start
21:00:47.978596+00:00 app worker_notifications.1 - - 4 TID-1vmqbk SendNotificationsWorker JID-53d24c9f745a64078541e3b5 INFO: start
21:00:48.010977+00:00 app worker_notifications.1 - - 4 TID-1vmp9g NotifyUsersWorker JID-fa80fdc7a83fee777d4bfbce INFO: done: 0.466 sec
21:00:48.098684+00:00 app worker_notifications.1 - - 4 TID-1vmpzc NotifyUsersWorker JID-348ae820d65ff75b56116cd5 INFO: start
21:00:48.257255+00:00 app worker_notifications.1 - - 4 TID-1vmpzc NotifyUsersWorker JID-348ae820d65ff75b56116cd5 INFO: done: 0.155 sec
21:00:48.893083+00:00 app worker_notifications.1 - - W, [2018-11-28T21:00:48.892957 #4]  WARN -- : [APN] Could not process notification 83089827: {"reason"=>"Unregistered", "timestamp"=>1540393349386} | status: 410 | headers: {":status"=>"410", "apns-id"=>"************************************"}
21:00:49.081991+00:00 app worker_notifications.1 - - W, [2018-11-28T21:00:49.081864 #4]  WARN -- : [APN] Could not process notification 83089828: {"reason"=>"Unregistered", "timestamp"=>1542844553494} | status: 410 | headers: {":status"=>"410", "apns-id"=>"************************************"}
21:00:50.046068+00:00 app worker_notifications.1 - - W, [2018-11-28T21:00:50.035331 #4]  WARN -- : [APN] Could not process notification 83089833: {"reason"=>"Unregistered", "timestamp"=>1541726616843} | status: 410 | headers: {":status"=>"410", "apns-id"=>"************************************"}
21:00:50.107293+00:00 app worker_notifications.1 - - 4 TID-1vmqbk SendNotificationsWorker JID-53d24c9f745a64078541e3b5 INFO: done: 2.129 sec
21:00:50.700405+00:00 app worker_notifications.1 - - 4 TID-1vmpg4 NotifyUsersWorker JID-5db30901976fd3bc8520e42c INFO: start
21:00:50.849734+00:00 app worker_notifications.1 - - 4 TID-1vmpg4 NotifyUsersWorker JID-5db30901976fd3bc8520e42c INFO: done: 0.149 sec
21:00:52.257534+00:00 app worker_notifications.1 - - 4 TID-1vmq5o NotifyUsersWorker JID-ebd880555f81d44f71f2fee6 INFO: start
21:00:52.536222+00:00 app worker_notifications.1 - - 4 TID-1vmoss SendNotificationsWorker JID-d7ddb8e013135b63e65e9b99 INFO: start
21:00:52.548387+00:00 app worker_notifications.1 - - 4 TID-1vmq5o NotifyUsersWorker JID-ebd880555f81d44f71f2fee6 INFO: done: 0.291 sec
21:00:53.366988+00:00 app worker_notifications.1 - - #<Thread:0x0000000008804e88@/app/vendor/bundle/ruby/2.5.0/gems/net-http2-0.18.0/lib/net-http2/client.rb:108 run> terminated with exception (report_on_exception is true):
21:00:53.367129+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/net-http2-0.18.0/lib/net-http2/client.rb:130:in `callback_or_raise': Socket was remotely closed (SocketError)
	from /app/vendor/bundle/ruby/2.5.0/gems/net-http2-0.18.0/lib/net-http2/client.rb:115:in `rescue in block (2 levels) in ensure_open'
	from /app/vendor/bundle/ruby/2.5.0/gems/net-http2-0.18.0/lib/net-http2/client.rb:109:in `block (2 levels) in ensure_open'
21:00:53.367465+00:00 app worker_notifications.1 - - Socket was remotely closed
21:00:53.367509+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/net-http2-0.18.0/lib/net-http2/client.rb:130:in `callback_or_raise'
21:00:53.367512+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/net-http2-0.18.0/lib/net-http2/client.rb:115:in `rescue in block (2 levels) in ensure_open'
21:00:53.367513+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/net-http2-0.18.0/lib/net-http2/client.rb:109:in `block (2 levels) in ensure_open'
21:00:53.524404+00:00 app worker_notifications.1 - - ** [NewRelic][2018-11-28 21:00:53 +0000 worker_notifications.1 (4)] INFO : Starting Agent shutdown
21:00:53.662182+00:00 app worker_notifications.1 - - 4 TID-1vmom4 NotifyUsersWorker JID-e11eba3f6bbeff0b7a1eaec9 INFO: start
21:00:53.788907+00:00 app worker_notifications.1 - - 4 TID-1vmom4 NotifyUsersWorker JID-e11eba3f6bbeff0b7a1eaec9 INFO: done: 0.127 sec
21:00:53.803936+00:00 app worker_notifications.1 - - 4 TID-1vmptg SendNotificationsWorker JID-9ee293f12e8ff55c40bed858 INFO: start
21:00:54.091621+00:00 app worker_notifications.1 - - 4 TID-1vmoss WARN: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context
21:00:54.091804+00:00 app worker_notifications.1 - - 4 TID-1vmoss WARN: {"context":"processor"}
21:00:54.091873+00:00 app worker_notifications.1 - - 4 TID-1vmoss WARN: ThreadError: can't alloc thread
21:00:54.091961+00:00 app worker_notifications.1 - - 4 TID-1vmoss WARN: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:23:in `new'
21:00:54.091964+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:23:in `safe_thread'
21:00:54.091965+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:65:in `start'
21:00:54.091966+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:96:in `block in processor_died'
21:00:54.091967+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:91:in `synchronize'
21:00:54.091969+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:91:in `processor_died'
21:00:54.091970+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:79:in `rescue in run'
21:00:54.091971+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:70:in `run'
21:00:54.091973+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
21:00:54.091974+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
21:00:54.092087+00:00 app worker_notifications.1 - - W, [2018-11-28T21:00:54.092021 #4]  WARN -- : **Airbrake: falling back to sync delivery because there are no running async workers
21:00:54.092184+00:00 app worker_notifications.1 - - 4 TID-1vmoss ERROR: !!! ERROR HANDLER THREW AN ERROR !!!
21:00:54.092247+00:00 app worker_notifications.1 - - 4 TID-1vmoss ERROR: attempted to build can't alloc thread with closed Airbrake instance
21:00:54.092352+00:00 app worker_notifications.1 - - 4 TID-1vmoss ERROR: /app/vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-2.10.0/lib/airbrake-ruby/notifier.rb:59:in `build_notice'
21:00:54.092354+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-2.10.0/lib/airbrake-ruby/notifier.rb:117:in `send_notice'
21:00:54.092356+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-2.10.0/lib/airbrake-ruby/notifier.rb:43:in `notify'
21:00:54.092357+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-2.10.0/lib/airbrake-ruby.rb:199:in `notify'
21:00:54.092358+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/airbrake-7.3.3/lib/airbrake/sidekiq.rb:19:in `notify_airbrake'
21:00:54.092360+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/exception_handler.rb:20:in `call'
21:00:54.092362+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/exception_handler.rb:20:in `block in handle_exception'
21:00:54.092363+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/exception_handler.rb:18:in `each'
21:00:54.092364+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/exception_handler.rb:18:in `handle_exception'
21:00:54.092366+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:18:in `rescue in watchdog'
21:00:54.092367+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:15:in `watchdog'
21:00:54.092368+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
21:00:54.092811+00:00 app worker_notifications.1 - - #<Thread:0x000000000d8a9410@/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:23 aborting> terminated with exception (report_on_exception is true):
21:00:54.092916+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:23:in `new': can't alloc thread (ThreadError)
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:23:in `safe_thread'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:65:in `start'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:96:in `block in processor_died'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:91:in `synchronize'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:91:in `processor_died'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:79:in `rescue in run'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:70:in `run'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by chrisrbnelson** [comment] 2019-02-14 01:20
Hey Mike

We've also been running into this issue since adding Sidekiq Pro, and from what I can tell it's related to Sidekiq Pro using `psubscribe`/`pmessage` on Redis connections that are pulled from the main `Sidekiq.redis` connection pool. 


```rb
# in lib/sidekiq/pro/config.rb
def listen
  while !@done
    begin
      Sidekiq.redis do |conn|                      # <------
        conn.psubscribe(CHANNEL) do |on|           # <------    
          on.pmessage do |pattern, channel, msg|   # <------
            message = Marshal.load(msg)
            @handlers.each do |watcher|
              watcher.notify(message.verb, message.payload)
            end
          end
        end
      end
    rescue Sidekiq::Shutdown
    rescue => ex
      handle_exception(ex)
      sleep 1
    end
  end
end
```

Once a Redis connection is in publish mode, it can't be used for other commands:

> Once the client enters the subscribed state it is not supposed to issue any other commands, except for additional SUBSCRIBE, PSUBSCRIBE, UNSUBSCRIBE and PUNSUBSCRIBE commands.
  https://redis.io/commands/subscribe

So when the connection is returned to the pool and picked up for other Sidekiq commands, it raises an `RuntimeError`  error. This in turn corrupts the enclosing thread leading to the `ThreadError`:

<img width="942" alt="screen shot 2019-02-14 at 12 18 36 pm" src="https://user-images.githubusercontent.com/645930/52755627-ada16d80-3052-11e9-8244-a1066d72efe9.png">

I believe Sidekiq Pro would need to maintain its own connection pool for pub/sub use to avoid this.

**Comment by mperham** [comment] 2019-02-14 14:53
@chrisrbnelson I'm not sure about your explanation. The connection is checked out and then `psubscribe` is called with a block.  **This is a long-lasting call** and shouldn't return unless the process is shutting down or an exception is received.  Once that psubscribe block returns, the Redis client library should ensure the connection is unsubscribed.

I'm worried about https://github.com/redis/redis-rb/blob/master/lib/redis/subscribe.rb#L50:

```ruby
      begin
        @client.call_loop([start, *channels], timeout) do |line|
          type, *rest = line
          sub.callbacks[type].call(*rest)
          unsubscribed = type == stop && rest.last == 0
          break if unsubscribed
        end
      ensure
        # No need to unsubscribe here. The real client closes the connection
        # whenever an exception is raised (see #ensure_connected).
      end
```

I wonder if there's an edge case where that comment is wrong.

**Comment by chrisrbnelson** [comment] 2019-02-16 03:52
@mperham 've run through the code and sprinkled it with logging and it does seem that there's a potential race condition there.

When Sidekiq receives a `TSTP` signal, the long lasting call in `config.listen` ends (due to receiving `Sidekiq::Shutdown`), and the connection it was using is [checked back in](https://github.com/mperham/connection_pool/blob/master/lib/connection_pool.rb#L65) to the available pool.

Meanwhile, jobs are still finishing up and being acknowledged by superfetch which is pulling connections from `Sidekiq.redis {}`. Since the tainted `psubscribe` connection is now sitting in that pool, it's likely to be picked up leading to the `Redis::CommandError`.

This fits with what we're seeing, as it only happens at the end of a Heroku deploy when Heroku sends the `TSPS` signal, and it always seems to be triggered inside `acknowledge`:

![screen shot 2019-02-16 at 2 47 57 pm](https://user-images.githubusercontent.com/645930/52894194-e7f93f00-31f9-11e9-9c62-7c3ba4dc46bf.png)

**Comment by mperham** [comment] 2019-02-16 21:18
Good, we're getting closer but I still don't see how the connection is tainted.  Sidekiq::Shutdown is an Interrupt, not a StandardError, so it won't be caught by a plain `rescue` block but the Redis client seems to handle everything correctly.  Redis::Client#ensure_connected disconnects the socket when it gets any type of Exception; the underlying socket won't be reused but rather reopened when the connection pool gives out the Redis::Client instance again.

```ruby
      rescue Exception
        disconnect
        raise
      end
```

**Comment by mperham** [comment] 2019-02-16 21:28
BTW, it would really help if we were all using the latest Redis client gem.  For all I know, this is a bug in Redis (gem) 4.0.2 and is fixed in 4.1.0 (the version I'm using locally).  Please make sure you can reproduce this bug with the latest version.  I don't see anything suspicious in the changelog but you never know:

https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#410

**Comment by chrisrbnelson** [comment] 2019-02-17 22:12
You're right - it looks like the connection should be closed there rather than ending up in back in the pool.

I've also had trouble replicating it locally yet it happens like clockwork at the end of the Heroku deploy, _I assume_ when receiving either the `TSPS` or `TERM`signals. I'll see if I can collect some more info in that environment.

> BTW, it would really help if we were all using the latest Redis client gem.

We're using 4.1.0 in all environments. :+1:

**Comment by ziaulrehman40** [comment] 2019-03-08 07:21
We are also seeing these errors of `ThreadError: can't alloc thread` and `ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context` randomly, we saw number of those at end of January and now in past few days we saw number of these again.

We are using redis gem `4.1` though not sure about redis server version. Also we are suing `sidekiq-cron` and `sidekiq-throttled`, i know those are not supported officially or anything, but i am mentioning them to make my report clearer.

**Comment by echan00** [comment] 2019-08-01 00:49
Curious to know what the situation is on this error. I am got this error (but not using Sidekiq pro), I am using https://github.com/JustinLove/autoscaler

**Comment by benoittgt** [comment] 2019-08-22 15:33
We bump airbrake to 9.3 and Redis to 4.1. We don't see more errors ATM so we didn't look further.

**Comment by mperham** [comment] 2020-03-25 17:43
I haven't seen this in quite a while; I'm going to assume it was an integration bug between gems that was fixed somehow.

**Closed by mperham** 2020-03-25 17:43 UTC
