### ISSUE TITLE
ActiveJob eager loading issue with sidekiq_options and Sidekiq Web

### ISSUE THREAD

**Issue by bilby91** [mperham/sidekiq#4497] opened 2020-03-18 14:13 UTC
Ruby version: 2.6.4p104
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.0.2

I'm experiencing an issue when using Rails `eager_load = true` while loading a rack app that hosts the Web UI. Problem seems to show up only on the jobs that use `sidekiq_options`. I'm running Rails 6.0.2.1

My `sidekiq.ru` file looks like this:

```
# frozen_string_literal: true

# If I uncomment this line, the web loads correctly
# require 'rails' 
require 'sidekiq/web'
require_relative './config/environment'

run Sidekiq::Web
```

The stacktrace is the following:

```
NoMethodError: undefined method `sidekiq_options' for MyJob:Class
  /var/www/app/app/jobs/my_job.rb:9:in `<class:MyJob>'
  /var/www/app/app/jobs/my_job.rb:4:in `<main>'
  /bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
  /bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
  /bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  /bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
  /bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
  /bundle/gems/elastic-apm-3.4.0/lib/elastic_apm/spies.rb:73:in `require'
  /bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:16:in `require'
  /bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:381:in `const_get'
  /bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:381:in `block (2 levels) in eager_load'
  /bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:723:in `block in ls'
  /bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:720:in `foreach'
  /bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:720:in `ls'
  /bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:376:in `block in eager_load'
  /bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:368:in `synchronize'
  /bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:368:in `eager_load'
  /bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:483:in `each'
  /bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:483:in `eager_load_all'
  /bundle/gems/railties-6.0.2.1/lib/rails/application/finisher.rb:122:in `block in <module:Finisher>'
  /bundle/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `instance_exec'
  /bundle/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `run'
  /bundle/gems/railties-6.0.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
  /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
  /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
  /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
  /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
  /bundle/gems/railties-6.0.2.1/lib/rails/initializable.rb:60:in `run_initializers'
  /bundle/gems/railties-6.0.2.1/lib/rails/application.rb:363:in `initialize!'
  /var/www/app/config/environment.rb:7:in `<top (required)>'
  /var/www/app/sidekiq.ru:5:in `require_relative'
  /var/www/app/sidekiq.ru:5:in `block in <main>'
  /bundle/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
  /bundle/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
  /bundle/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
  /bundle/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
  /bundle/gems/rack-2.2.2/lib/rack/server.rb:349:in `build_app_and_options_from_config'
  /bundle/gems/rack-2.2.2/lib/rack/server.rb:249:in `app'
  /bundle/gems/rack-2.2.2/lib/rack/server.rb:422:in `wrapped_app'
  /bundle/gems/rack-2.2.2/lib/rack/server.rb:312:in `block in start'
  /bundle/gems/rack-2.2.2/lib/rack/server.rb:379:in `handle_profiling'
  /bundle/gems/rack-2.2.2/lib/rack/server.rb:311:in `start'
  /bundle/gems/rack-2.2.2/lib/rack/server.rb:168:in `start'
  /bundle/gems/rack-2.2.2/bin/rackup:5:in `<top (required)>'
  /bundle/bin/rackup:23:in `load'
  /bundle/bin/rackup:23:in `<top (required)>'
```

The interesting piece as pointed out in the `sidekiq.ru` file, is that, if I `require 'rails'` before anything, the web loads correctly. I'm not sure if this is a Sidekiq issue or a Rails issue. I know the `sidekiq_options` support using ActiveJob is fairly new so there might be a bug.

Thanks!

**Comment by mperham** [comment] 2020-03-18 14:17
You cut off the error message?

**Comment by bilby91** [comment] 2020-03-18 14:18
My bad, this is the error.

```
NoMethodError: undefined method `sidekiq_options' for MyJob:Class
```

I'm going to update the stacktrace.

**Comment by mperham** [comment] 2020-03-18 14:29
Upgrade Sidekiq, mate.

**Comment by bilby91** [comment] 2020-03-18 14:36
@mperham Same issue with Sidekiq 6.0.5

**Comment by mperham** [comment] 2020-03-18 15:16
Ok, I thought you were hitting the issues fixed in 6.0.4. Investigating.

**Comment by mperham** [comment] 2020-03-18 15:23
It sounds like you might have a customized app which does not boot as normal.  My Rails app calls config/environment.rb -> config/application.rb -> rails.  If your config/application.rb isn't requiring rails somehow, perhaps that's the underlying issue.

Sidekiq expects ActiveJob to boot and fire its callbacks upon boot so that Sidekiq can hook into ActiveJob::Base: https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/rails.rb#L19-L21 I'm guessing your Rack app might be trimming something and breaking this pattern.

**Comment by bilby91** [comment] 2020-03-18 15:29
This is what my `config/application.rb` looks like:

```
# frozen_string_literal: true

require_relative 'boot'

require 'rails'
# Pick the frameworks you want:
require 'active_model/railtie'
require 'active_record/railtie'
require 'action_controller/railtie'
require 'rails/test_unit/railtie'
require 'active_job/railtie'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module App
  # :nodoc:
  class Application < Rails::Application
    config.active_record.schema_format = :sql

    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 6.0

    config.active_job.queue_adapter = :sidekiq

    # Add lib to autoload_paths so that we don't need to `require` them.
    config.autoload_paths += [
      Rails.root.join('lib')
    ]

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration can go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded after loading
    # the framework and any gems in your application.

    # Only loads a smaller set of middleware suitable for API only apps.
    # Middleware like session, flash, cookies can be added back manually.
    # Skip views, helpers and assets when generating a new resource.
    config.api_only = true

    # Adds /healthcheck endpoint
    config.middleware.insert 0, Healthcheck::Middleware
  end
end
```

If that was the case, this wouldn't be a problem for my web tier as well ?  We run `puma` for the web tier (independent from Sidekiq Web rack app) and it's not having any issues while loading.

**Comment by mperham** [comment] 2020-03-18 15:47
When Sidekiq boots your Rails app, it does this:

```ruby
require "rails"
require "sidekiq/rails"
require File.expand_path("#{options[:require]}/config/environment.rb")
```

I can't explain why your app is failing but I'd suggest you replace your top set of requires with `require 'rails/all'` and see if the app boots then.

**Comment by mperham** [comment] 2020-03-18 15:49
Ah, the issue is  that you are requiring sidekiq/web before you've loaded any Rails code, which means Sidekiq doesn't load its Rails integration:

```
require "sidekiq/rails" if defined?(::Rails::Engine)
```

**Closed by mperham** 2020-03-18 15:49 UTC

**Comment by bilby91** [comment] 2020-03-18 15:52
Ah! Good catch, flipping this seems to have solved it:

```
require_relative './config/environment'
require 'sidekiq/web'
```

Thanks!!
