### ISSUE TITLE
Logs show 'undefined method `retrieve_work' for nil:NilClass' on startup

### ISSUE THREAD

**Issue by brrygrdn** [mperham/sidekiq#2983] opened 2016-05-23 18:11 UTC
We are currently upgrading our system's infrastructure from running directly on AWS to deploying it as containers into Mesos.

In order to benefit from the `timed_fetch` reliability strategy for our new environment we have upgraded Sidekiq from 3.5.2 > 4.1.2 and Sidekiq Pro from 2.1.4 > 3.2.1.

After making the upgrade we noticed a repeated error trace immediately after boot on our workers:

```
Error fetching job: undefined method `retrieve_work' for nil:NilClass
```

See [full trace](https://gist.github.com/brrygrdn/30429506b37c2d1a294967ab0d6cbe18)

The workers go on to process the queue successfully, but we have found we encounter this error repeatedly on bringing up a new worker and were at a loss as to the root cause. It does not obviously relate to the job failure at the start of the trace, which is a known issue we have with some malformed payloads.

Would you have any pointers in terms of debugging this issue? Please let me know if I've omitted anything relevant.

__Versions__

We are using:
- sidekiq 4.1.2
- sidekiq-pro 3.2.1
- rails 4.1.15
- ruby 2.1.2
- ubuntu 14.04.4

__Backtrace__

[Gist](https://gist.github.com/brrygrdn/30429506b37c2d1a294967ab0d6cbe18)

__config/initialisers/sidekiq.yml__
```
require 'sidekiq/web'
require 'sidekiq/pro/web'

sidekiq_extensions_config = Rails.root.join('config', 'sidekiq_extensions.yml')
sidekiq_extensions = Isomer.configure(:yaml, file: sidekiq_extensions_config, base: Rails.env) do |config|
  config.parameter :max_failure_count, default: 5_000 # Set to 10_000 in the YAML file
  config.parameter :username
  config.parameter :password
end

Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.timed_fetch!
  config.reliable_scheduler!

  config.redis = { url: REDIS_CONFIG.url, namespace: 'resque' }

  config.server_middleware do |chain|
    require 'sidekiq/middleware/server/statsd'
    chain.add Sidekiq::Middleware::Server::Statsd, client: ARCHIMEDES.service
  end

  ActiveSupport::Dependencies.mechanism = :require
  ActiveRecord::Base.establish_connection
end

Sidekiq::Logging.logger.level = Logger::WARN

Sidekiq.configure_client do |config|
  config.redis = { url: REDIS_CONFIG.url, namespace: 'resque' }
end

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  username == sidekiq_extensions.username &&
  password == sidekiq_extensions.password
end
```

**Comment by seuros** [comment] 2016-05-23 18:26
did you upgrade 1 major version at once ?

**Comment by brrygrdn** [comment] 2016-05-23 18:58
@seuros, yes, we migrated in a single pass.

**Comment by seuros** [comment] 2016-05-23 19:06
Check the changelogs, https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md

**Comment by mperham** [comment] 2016-05-23 19:26
> "enqueued_at":1452792320.684064.0000427

You are hitting a Pro bug, #2639, that was fixed in 2.1.3 which created invalid JSON. There's no script to fix the invalid jobs.

I can't explain why your fetch strategy is nil.  It looks like an impossible case in processor.rb so I'm very confused.

**Comment by brrygrdn** [comment] 2016-05-24 12:54
Thanks for the replies, we're still debugging ourselves and have a quick update. We let the upgraded version run for a while to soak test it but found that eventually it stopped being able to process items.

We took a copy of the Redis data in the bad state to perform some further debugging. Wiping and re-loading the problem Redis data between each test we have tested the following:

- Sidekiq Pro 2.1.5: successfully processes
- Sidekiq Pro 3.0.0: successfully processes
- Sidekiq Pro 3.0.6: successfully processes
- Sidekiq Pro 3.1.0: successfully processes
- Sidekiq Pro 3.1.0, with `timed_fetch`: unable to process

We repeated the final test after clearing the retry and dead queues from the data set but to no avail. 

At present, we think the issue may relate to a set of batches that would generally not exist in our staging environment as they are created by cronjobs - we would generally only trigger these on demand for specific testing in staging as they relate to production data.

**Comment by brrygrdn** [comment] 2016-05-24 16:34
We've done some further debugging and confirmed that the issue is with the contents of the `pending` key in our Redis snapshot. As soon as we clear that key, the queue starts to process again.

Looking at the data in pending, it seems to be a mix of long-tail retries and current jobs. I can confirm that the job observed as failing at the start of the backtrace, which you [mentioned](https://github.com/mperham/sidekiq/issues/2983#issuecomment-221070163) above, is in the `pending` set. I don't think we can say for sure that is what is poisoning the set, so we are still unsure on the ultimate root cause and means to prevent the `pending` queue falling into a failing state again.

**Comment by mperham** [comment] 2016-05-24 16:44
That's really odd.  The timed_fetch code doesn't do anything with the job payload - a malformed job should not matter to it.  How big is the pending set?

**Comment by brrygrdn** [comment] 2016-05-24 16:49
It has 98 items.

It is really curious, if we halt and resume a `timed_fetch` worker on a 'clean' Redis we see it pick up the contents of `pending` and work with it. It is specifically this data set that has the problem.

**Comment by brrygrdn** [comment] 2016-05-24 16:56
I think you've already answered this with your comment, but I just wanted to clarify my understanding.

If a job is attempted by `reliable_fetch`, fails and is re-attempted by `timed_fetch` on either side of the upgrade, the payload is identical in both cases, i.e. the retry doesn't have any `timed_fetch` information missing?

**Comment by mperham** [comment] 2016-05-24 17:00
Correct.  The fetch strategies pull jobs and never alter the payload.  Only enqueuing alters the payload because of the `enqueued_at` property.

**Comment by brrygrdn** [comment] 2016-05-24 17:07
Thanks for confirming!

**Comment by TheTeaNerd** [comment] 2016-05-25 09:04
Update: the poison jobs do seem to be affected by #2639, we're working on fixing their metadata and hope this will enable the upgrade to continue. Will update later and possibly close this issue if this is confirmed to be #2639.

**Comment by brrygrdn** [comment] 2016-05-25 12:18
We've been able to successfully fix the `enqueued_at` up for the jobs suffering from malformed values and are now able to process successfully post-upgrade.

Our internal analysis is that the root cause is ultimately due to infrequent upgrades on our part coupled with some long-lived failed jobs still in the retry queue. It's not going to be a very common upgrade path for users to jump from 2.1.3 to the latest release with the `timed_fetch` strategy under these circumstances, so we're happy to close the issue unless there's any further information we can provide.

**Comment by mperham** [comment] 2016-05-25 16:06
Thanks for the thorough report, @brrygrdn, and sorry for the trouble.  Glad you got everything resolved.

**Closed by mperham** 2016-05-25 16:06 UTC
