### ISSUE TITLE
Error introduced in 6.5.4 - `uninitialized constant Sidekiq::Component`

### ISSUE THREAD

**Issue by jensenbox** [mperham/sidekiq#5463] opened 2022-08-09 23:06 UTC
Ruby version: 3.1.2
Rails version: 7.0.3.1
Sidekiq / Pro / Enterprise version(s): 6.5.4

I was able to pin at 6.5.3 and everything works as expected. Upgrading to 6.5.4 I receive the following:

```
    /usr/local/bundle/gems/sidekiq-6.5.4/lib/sidekiq/job_retry.rb:66:in `<class:JobRetry>': uninitialized constant Sidekiq::Component (NameError)

    include Sidekiq::Component
                   ^^^^^^^^^^^
    Did you mean?  CompositeIO
```

```
        from /usr/local/bundle/gems/sidekiq-6.5.4/lib/sidekiq/job_retry.rb:61:in `<module:Sidekiq>'
        from /usr/local/bundle/gems/sidekiq-6.5.4/lib/sidekiq/job_retry.rb:6:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /usr/local/bundle/gems/sidekiq-status-2.1.3/lib/sidekiq-status/server_middleware.rb:2:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /usr/local/bundle/gems/sidekiq-status-2.1.3/lib/sidekiq-status.rb:6:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:55:in `each'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:55:in `block in require'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:44:in `each'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:44:in `require'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler.rb:188:in `require'
        from /usr/src/app/config/application.rb:21:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /usr/local/bundle/gems/railties-7.0.3.1/lib/rails/commands/server/server_command.rb:137:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /usr/local/bundle/gems/railties-7.0.3.1/lib/rails/commands/server/server_command.rb:134:in `perform'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/railties-7.0.3.1/lib/rails/command/base.rb:87:in `perform'
        from /usr/local/bundle/gems/railties-7.0.3.1/lib/rails/command.rb:48:in `invoke'
        from /usr/local/bundle/gems/railties-7.0.3.1/lib/rails/commands.rb:18:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:5:in `<main>'

```

I think the removal of the `require` here is causing a downstream effect: https://github.com/mperham/sidekiq/compare/v6.5.3..v6.5.4#diff-a2a78bd5586e1300341bb91dc8be382aa98126dcde11bd507fe9886d2e643ee7L3

**Comment by mperham** [comment] 2022-08-09 23:08
Dupe of #5462

**Closed** 2022-08-09 23:08 UTC
