### ISSUE TITLE
Failing job is enqueued many times

### ISSUE THREAD

**Issue by alepore** [mperham/sidekiq#3356] opened 2017-02-15 16:42 UTC
Ruby version: 2.4.0
Sidekiq / Pro / Enterprise version(s): 5.0.0.beta1
Rails version: 5.0.1

Hello!
If i run this job on Sidekiq 5.0.0.beta1:

```ruby
class TestJob
  include Sidekiq::Worker

  def perform
    raise
  end
end

...

TestJob.perform_async
```

After some minutes i have this situation:

<img width="761" alt="screen shot 2017-02-15 at 17 33 03" src="https://cloud.githubusercontent.com/assets/557414/22984180/db605cb4-f3a4-11e6-9607-f5dcc915da82.png">

The Retry queue keeps growing forever with duplicates of the same job.
Version 4.2.9 is working as expected (there's just one job entry).

In one occasion i also found the "Scheduled" queue filled with thousand entries of the same job, but i can't reproduce it right now.

Thanks!

**Comment by mperham** [comment] 2017-02-15 18:43
I can reproduce the problem, thanks for the steps.  Investigating now.

**Comment by mperham** [comment] 2017-02-15 19:14
Fixed in 812e0f17, you can run against the 5-0 branch if you want to verify.

**Closed** 2017-02-15 19:15 UTC

**Comment by monfresh** [comment] 2017-09-22 17:24
I'm running into a similar issue with Sidekiq 5.0.4, but I'm not sure if it's a bug or not. 

In our [Sidekiq initializer](https://github.com/18F/identity-idp/blob/master/config/initializers/sidekiq.rb#L19) (Rails app), we are calling a [module](https://github.com/18F/identity-idp/blob/master/app/services/worker_health_checker.rb) which lives in a path that Rails autoloads. 

This results in the following error when triggering a background job (such as sending an email), then making a change to a file that Rails reloads automatically, then sending another email:
```
WARN -- : ArgumentError: A copy of WorkerHealthChecker::Middleware has been removed from the module tree but is still active!
```
The strange thing is that even though Sidekiq considers this a failed job, the email does get sent successfully. The end result is that I keep getting the same email over and over because Sidekiq thinks the job has failed and so it keeps retrying.

We can fix this by moving the `WorkerHealthChecker` module from `app/services` to `lib`, which isn't in Rails autoload paths, but I'm curious as to why emails are successfully sent if the Sidekiq job failed.

Thoughts?

**Comment by mperham** [comment] 2017-09-22 18:17
@monfresh Please don't add onto existing closed issues.  Open your own new issue.

**Comment by monfresh** [comment] 2017-09-22 21:00
Will do. Sorry about that.
