### ISSUE TITLE
Upgrades to 6.5.4 are broken

### ISSUE THREAD

**Issue by rebeccajfriedman** [mperham/sidekiq#5464] opened 2022-08-10 13:11 UTC
Ruby version: 3.1.1
Rails version: 7.0.3.1
Sidekiq / Pro / Enterprise version(s): **6.5.4**

In `6.5.4`, `include Sidekiq::Component` is used before Component is required: https://github.com/mperham/sidekiq/compare/v6.5.1...v6.5.4#diff-db72e89711ace18a479c59a7cbb5cbf929670cd7f73b334dfe4d8c338af0e280R9

```
NameError: uninitialized constant Sidekiq::Component

    include Sidekiq::Component
                    ^^^^^^^^^^^
Did you mean?  CompositeIO
/app/config/initializers/sidekiq.rb:4:in `<main>'
/app/config/environment.rb:8:in `<main>'
```

**Comment by mperham** [comment] 2022-08-10 13:39
Dupe of #5462

**Closed** 2022-08-10 16:27 UTC
