### ISSUE TITLE
ERP_LIMITER 

### ISSUE THREAD

**Issue by ayazahmadtarar-pikessoft** [mperham/sidekiq#4090] opened 2019-01-31 14:30 UTC
Ruby version:
Sidekiq / Pro / Enterprise version(s):

I amusing LIMITER = Sidekiq::Limiter.concurrent('salesforce', 25, wait_timeout: 5, lock_timeout: 30) for salesforce calls but still getting salesforce concurrent request errors

 Wanted to ask Sidekiq::Limiter.concurrent concurrency works across processes (sidekiq instances ) or Sidekiq workers (of process)

**Comment by mperham** [comment] 2019-01-31 17:18
It works across threads and processes.  If your calls are taking longer than lock_timeout, you can get concurrent errors.

**Comment by epergo** [comment] 2019-02-07 11:13
Same here, we started having problems with the concurrent lock after upgrading sidekiq enterprise to `1.7.2`, in only fails when the 2 requests for obtaining the lock are done in the same second.

request1 -> "2019-02-07 03:47:27.583"
request2 -> "2019-02-07 03:47:27.581"

**Comment by pacoguzman** [comment] 2019-02-07 12:54
Just to complete the previous comment, our current version is `1.6.1` and the limiters were created with `1.6.1` in case that means something.

**Comment by pacoguzman** [comment] 2019-02-07 13:18
Going back to the `1.6.1` and the number of `reclaimed` entries just stopped to increase, no other changes on  the codebase.

**Comment by mperham** [comment] 2019-02-07 17:18
Thanks for the details, that's useful for debugging. I'm investigating but there's only two changes to the concurrent lock between 1.6.1 and 1.7.2: using the monotonic clock and fixing a bug in calling the `lock` Lua function.  That bug was part of the reclaim logic.

None of you are clear in your bug reports: how do you know the current behavior is wrong?  Create a timeline for me and explain what you expected to happen.

If you can create a script which reproduces your problem locally, I would be happy to diagnose.

**Comment by pacoguzman** [comment] 2019-02-08 19:10
We're trying to reproduce the problem in our local machines without luck for the moment, but the workers that we use could be summarized in something like

```ruby
class ConcurrentWorker
  include Sidekiq::Worker

  def perform(key)
    Sidekiq.logger.info("key: #{key}")

    Clients.lock_manager.perform(key) do
      code = Clients.redis.get(key)
      Sidekiq.logger.info("lock: #{key} | #{code}")
      sleep 1 + rand(0.09)

      Clients.redis.set(key, code + 1)
    end
  end
end
```

We use a lock of size 1, to control the access to an incremental counter, so we have a sequence of numbers to generate some documents.

What we saw is that some documents share the same sequence value. Like if the lock is not locking the different processes.

**Comment by mperham** [comment] 2019-02-08 19:14
Use the INCR command and you don’t need a lock at all.

**Comment by pacoguzman** [comment] 2019-02-08 19:45
That's a simplification of our code.

I do not get the idea of using just INCR, could you extend?

The sequence must be incremental without gaps and the code could fail so we
should control only one process is modifying the sequence.

We use different processes in different boxes too.

**Comment by pacoguzman** [comment] 2019-02-08 19:58
Sorry I forgot, to decode our abstraction to create limiters

```ruby
class ConcurrentWorker
  include Sidekiq::Worker

  def perform(key)
    Sidekiq.logger.info("key: #{key}")

    limiter = Sidekiq::Limiter.concurrent(key, 1,
                                          wait_timeout: 5,
                                          lock_timeout: 5.minutes)
    limiter.within_limit do
      code = Clients.redis.get(key)
      Sidekiq.logger.info("lock: #{key} | #{code}")
      sleep 1 + rand(0.09)

      Clients.redis.set(key, code + 1)
    end
  end
end
```

One thing to notice is that when we bumped to `1.7.2` we saw a substantial number of reclaimed locks, when before we had none. That's why we thought something is not correct. Those reclaims makes to reuse same numbers on different instances.

**Comment by mperham** [comment] 2019-02-08 20:23
The Redis INCR command is designed to implement distributed lock free counters exactly what you were trying to do. AFAICT you don’t need a concurrent limiter at all if you use it.

**Comment by pacoguzman** [comment] 2019-02-09 07:05
Sorry but we cannot use a Redis `INCR` for our problem, based on the documentation

> You can use a concurrent limiter of size 1 to make a distributed mutex, ensuring that only one process can execute a block at a time.

That's what we need but for some reason the bump makes the number of reclaimed locks started to count.

<img width="340" alt="screenshot 2019-02-09 at 07 59 21" src="https://user-images.githubusercontent.com/10926/52517772-a4726400-2c40-11e9-8d2b-187272f8a79d.png">

Is it only `lock_timeout` the reason of `reclaimed` items to happen? Could be possible that having a difference in the clocks of the different instances make this happen more frequently?

**Comment by mperham** [comment] 2019-02-09 17:09
Yes, having unsync'd clocks can be a serious problem.  Most people are running on some sort of cloud platform that uses NTP but certainly double check that your clocks are accurate.

According to the code you are showing there, you can replace all of that code with:

```ruby
value = Sidekiq.redis {|c| c.incr(key) }
```

I'd be curious to know more about why INCR can't implement your distributed counter.

https://redis.io/commands/incr#pattern-counter

`reclaimed` can mean that a Sidekiq process is crashing while holding the lock so after the lock_timeout, another process reclaims that lock.  You aren't seeing overages, which is a good sign.  That will trigger if the within_limit block actually takes longer than lock_timeout.  So, it's possible that your Sidekiq version upgrade (maybe you upgraded a bunch of other gems all at once) could have introduced a more frequent crashing bug.  If you aren't crashing, double check the clocks.

**Comment by dnnyjns** [comment] 2019-02-23 22:37
I'm also experiencing a high amount of reclaimed jobs when using the concurrent rate limiter on sidekiq-ent v1.8.0. The rate limiter works correctly when using only 1 worker, but as soon as we add in more workers we run into problems. As you mentioned above, this is happening because the monotonic clocks are not being synchronized between workers. If I have 2 workers on 2 different machines, then machine #1 could have an initial monotonic clock value of 10000 and machine #2 could be set at 100000. This would result in machine #2 always reclaiming locks from machine #1 when the limiter is full.

The clocks on our machines are accurate as they are setup with timesynchd. We've researched setting up NTP, but we don't believe that NTP will fix the issue as NPT will only affect the ticks of the monotonic clock, but not the initial value. It is my understanding that the monotonic clock will always be initialized from an arbitrary point and can only increments forward.

Do you have any other recommendations?

**Comment by mperham** [comment] 2019-02-23 22:46
Thanks @dnnyjns, you have figured out the actual issue: monotonic clock values are not comparable across processes.  I didn't know this; will be fixed on Monday.

**Comment by mperham** [comment] 2019-02-23 22:57
If someone wants to test this patch, lmk how it works for you:

```
--- a/lib/sidekiq-ent/limiter/concurrent.rb
+++ b/lib/sidekiq-ent/limiter/concurrent.rb
@@ -178,7 +178,7 @@ module Sidekiq
         start = ::Process.clock_gettime(::Process::CLOCK_MONOTONIC)
         expiry, token = nil
 
-        t = ::Process.clock_gettime(::Process::CLOCK_MONOTONIC)
+        t = Time.now.to_f
         expiry = t + @lock_for
         token = Sidekiq::Enterprise::Scripting.call(:limiter_concurrent_lock,
                                              [@free, @used, @key],
@@ -194,7 +194,7 @@ module Sidekiq
             candidate = conn.brpoplpush(@free, @pend, diff.to_f.ceil.to_i)
 
             if candidate
-              t = ::Process.clock_gettime(::Process::CLOCK_MONOTONIC)
+              t = Time.now.to_f
               expiry = t + @lock_for
               token = Sidekiq::Enterprise::Scripting.call(:limiter_concurrent_lock,
                                                    [@pend, @used, @key],
```

**Comment by mperham** [comment] 2019-02-27 18:40
@dnnyjns @pacoguzman Can someone confirm that patch solves your reclaims?  I can get a 1.8.2 release out with the fix.

**Comment by pacoguzman** [comment] 2019-02-27 18:54
We planned to test it next Monday. Thanks for the update.

**Comment by dnnyjns** [comment] 2019-03-01 17:13
@mperham I've tested the patch and everything appears to be working great. Thanks!

**Comment by mperham** [comment] 2019-03-01 17:22
Wonderful, I’m waiting on a few i18n fixes and will get a 1.8 patch release out early next week.

**Comment by pacoguzman** [comment] 2019-03-01 18:19
Great news thanks!

**Comment by mperham** [comment] 2019-03-05 16:37
1.8.1 has been released with this fix.

**Closed by mperham** 2019-03-05 16:37 UTC

**Comment by mperham** [comment] 2019-03-05 16:38
@dnnyjns @pacoguzman Thank you for your help with this issue!
