### ISSUE TITLE
Update Logging wiki for custom log formatter

### ISSUE THREAD

**Issue by FTLam11** [mperham/sidekiq#4244] opened 2019-09-05 04:34 UTC
Ruby version: 2.6.4
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.0.0

Please include your initializer and any error message with the full backtrace.
```ruby
module Sidekiq
  class Logger < ::Logger
    module Formatters
      class ExtraPretty < Base
        def call(severity, time, program_name, message)
          "#{time.utc.iso8601(3)} pid=#{::Process.pid} tid=#{tid}#{format_context} [#{severity}] #{message}\n"
        end
      end
    end
  end
end

Sidekiq.configure_server do |config|
  config.redis = { url: ENV["REDIS_URL"] }
  config.log_formatter = Sidekiq::Logger::Formatters::ExtraPretty.new
  config.logger.formatter = config.log_formatter
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV["REDIS_URL"] }
end
```

Hi, I'm using Sidekiq in a Rails engine and was able to customize the log format (just putting brackets around the level tag). However, what is the relation between `Sidekiq.log_formatter` and the `formatter` attribute for `Sidekiq.logger`? Am I wrong in assuming any relationship?

Here is the output when starting up Sidekiq with only `log_formatter` set to the custom formatter:

```
2019-09-05T04:25:25.386Z pid=70094 tid=ovd7zo2k2 INFO: Booting Sidekiq 6.0.0 with redis options {:url=>"redis://localhost:6379/1", :id=>"Sidekiq-server-PID-70094"}
2019-09-05T04:25:25.909Z pid=70094 tid=ovd7zo2k2 INFO: Running in ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]
2019-09-05T04:25:25.909Z pid=70094 tid=ovd7zo2k2 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2019-09-05T04:25:25.909Z pid=70094 tid=ovd7zo2k2 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2019-09-05T04:25:25.913Z pid=70094 tid=ovd7zo2k2 INFO: Starting processing, hit Ctrl-C to stop
```

With `log_formatter` and `logger.formatter` set to the custom formatter:

```
2019-09-05T04:27:22.790Z pid=70329 tid=ours0jldp INFO: Booting Sidekiq 6.0.0 with redis options {:url=>"redis://localhost:6379/1", :id=>"Sidekiq-server-PID-70329"}
2019-09-05T04:27:23.285Z pid=70329 tid=ours0jldp [INFO] Running in ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]
2019-09-05T04:27:23.285Z pid=70329 tid=ours0jldp [INFO] See LICENSE and the LGPL-3.0 for licensing details.
2019-09-05T04:27:23.285Z pid=70329 tid=ours0jldp [INFO] Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2019-09-05T04:27:23.287Z pid=70329 tid=ours0jldp [INFO] Starting processing, hit Ctrl-C to stop
```

With `Sidekiq.logger.formatter = Sidekiq::Logger::Formatters::ExtraPretty.new`, not setting either `log_formatter` or `logger.formatter`:

```
2019-09-05T04:28:37.661Z pid=70557 tid=owmk8tas9 INFO: Booting Sidekiq 6.0.0 with redis options {:url=>"redis://localhost:6379/1", :id=>"Sidekiq-server-PID-70557"}


               m,
               `$b
          .ss,  $$:         .,d$
          `$$P,d$P'    .,md$P"'
           ,$$$$$b/md$$$P^'
         .d$$$$$$/$$$P'
         $$^' `"/$$$'       ____  _     _      _    _
         $:     ,$$:       / ___|(_) __| | ___| | _(_) __ _
         `b     :$$        \___ \| |/ _` |/ _ \ |/ / |/ _` |
                $$:         ___) | | (_| |  __/   <| | (_| |
                $$         |____/|_|\__,_|\___|_|\_\_|\__, |
              .d$$                                       |_|


2019-09-05T04:28:38.270Z pid=70557 tid=owmk8tas9 [INFO] Running in ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]
2019-09-05T04:28:38.270Z pid=70557 tid=owmk8tas9 [INFO] See LICENSE and the LGPL-3.0 for licensing details.
2019-09-05T04:28:38.270Z pid=70557 tid=owmk8tas9 [INFO] Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2019-09-05T04:28:38.274Z pid=70557 tid=owmk8tas9 [INFO] Starting processing, hit Ctrl-C to stop
``` 

I assume the last method is the way to go? If so, the [Output Format wiki](https://github.com/mperham/sidekiq/wiki/Logging#output-format) could be updated to reflect that.

**Comment by mperham** [comment] 2019-09-05 16:11
I see, yep.  Changing the log_formatter does not re-create a new Logger instance.

**Comment by mperham** [comment] 2019-09-05 16:48
The issue is that you set `config.redis` before the log format.  The redis connection is eager created and logs its config, thus creating the logger before the format is set. Should we raise an error if log_format isn't set before the Logger is created?  Or should we reset the Logger? cc @Tensho

**Comment by mperham** [comment] 2019-09-05 19:12
Just fixed on master. log_formatter= now resets @logger.

**Closed by mperham** 2019-09-05 19:12 UTC

**Comment by Tensho** [comment] 2019-09-05 19:29
I have no good ideas how to force the log formatter to be assigned before other configuration. I would consider getting an error for the unspecified formatter before logger a little bit weird. Reset logger could be an option, but I'm not sure is it intuitive for the experienced rubists. Probably it's reasonable to drop `log_formatter` accessor at `Sidekiq` module level (configuration) and leave only `logger` accessor allowing a user to specify required formatter independently:
```
Sidekiq.configure_server do |config|
  config.logger.formatter = Sidekiq::Logger::Formatters::ExtraPretty.new
end
```
But that doesn't resolve the issue with the eager Redis connection logging. If I understand correctly Rails resolves the similar problem with simply putting `log_formatter` above `logger` assignment in the environment config file:
```
# Use default logging formatter so that PID and timestamp are not suppressed.
config.log_formatter = ::Logger::Formatter.new

# Use a different logger for distributed setups.
# require 'syslog/logger'
# config.logger = ActiveSupport::TaggedLogging.new(Syslog::Logger.new 'app-name')

if ENV['RAILS_LOG_TO_STDOUT'].present?
  logger           = ActiveSupport::Logger.new(STDOUT)
  logger.formatter = config.log_formatter
  config.logger    = ActiveSupport::TaggedLogging.new(logger)
end
```

BTW, what is the reason to keep `redis=` eager – fast fail on the wrong configuration?
