### ISSUE TITLE
Passing the timeout as a positional argument is deprecated, it should be passed as a keyword argument

### ISSUE THREAD

**Issue by ldlgds2** [mperham/sidekiq#5488] opened 2022-08-23 22:00 UTC
Ruby version: 3.0.4
Rails version: 6.1.6.1
Sidekiq / Pro / Enterprise version(s): 6.5.5

```
Passing the timeout as a positional argument is deprecated, it should be passed as a keyword argument:
redis.brpop("queue:default", timeout: 2)(called from: /usr/local/bundle/gems/sidekiq-6.5.5/lib/sidekiq/fetch.rb:49:in 'block in retrieve_work')
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /usr/local/bundle/gems/sidekiq-6.5.5/lib/sidekiq/launcher.rb:168:in 'block (2 levels) in ❤')
```

Gem redis 4.8.0 seems to be issue, downgrading to 4.7.1 fixed it temporarily.

**Comment by mperham** [comment] 2022-08-23 22:04
Already fixed on main, leaving open so others will see it and not open duplicates. #5484 #5485 #5486

**Comment by tisba** [comment] 2022-08-25 12:07
Not sure I'm overlooking something. But https://github.com/mperham/sidekiq/commit/09dacfed8f3f0b42833122b138639d22c71e3d56#diff-0c49098f0471d2ffa897441bd05c7d24c04ce480e66cb534b194a4bb15e0b201R168 is probably not fixing the warning

```
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /usr/local/bundle/gems/sidekiq-6.5.5/lib/sidekiq/launcher.rb:168:in 'block (2 levels) in ❤')
```

**Comment by schorsch** [comment] 2022-08-25 12:45
@tisba seems like all args where converted to the required array syntax by v4.8 of the redis gem https://github.com/redis/redis-rb/blob/v4.8.0/lib/redis/commands/sets.rb#L22

**Comment by rsl** [comment] 2022-08-29 13:39
this is eating up logging like mad for us. is there a way to put out a fix soon? would be awesome. our logging keeps filling up.

**Comment by mperham** [comment] 2022-08-29 16:20
@rsl No one is forcing you to use Redis 4.8.0. You can downgrade.

**Comment by rsl** [comment] 2022-08-29 20:29
wasn't trying to be rude. just asking a question. not sure if there's a hold up on releasing a new gem version or something?

**Comment by ryanb** [comment] 2022-08-29 21:25
Looks like Sidekiq 6.5.6 is out which includes this fix.

**Comment by aaricpittman** [comment] 2022-08-30 21:05
Just to confirm, `6.5.6` should fix the issue? Or do I also need to downgrade the `redis` gem?

Because I'm still seeing the error and we are on `6.5.6`.

**Comment by mperham** [comment] 2022-08-30 22:07
@aaricpittman It should. If you are still seeing the issue, it's possibly due to a 3rd party plugin.

**Comment by coderberry** [comment] 2022-08-31 21:22
I am seeing these error come from the sidekiq-throttled gem ([issue link](https://github.com/ixti/sidekiq-throttled/pull/13)).

**Closed** 2022-09-09 19:45 UTC

**Comment by virusman** [comment] 2024-04-22 03:48
@coderberry Thanks, I found the issue in my project to be caused by an outdated version of `sidekiq-limit_fetch`.
