### ISSUE TITLE
ActiveRecord::StatementInvalid: Errno::EBADF: Bad file descriptor

### ISSUE THREAD

**Issue by wksmall** [mperham/sidekiq#2502] opened 2015-08-20 19:10 UTC
Lately we've been seeing a number of these errors which ultimately cause a sidekiq job to fail. There doesn't seem to be any pattern to the point where the error occurs. In other sidekiq issues, I read that we should be running the latest gems, particularly mysql2 which we updated last week. We are still seeing the error however. Our current configuration includes the following:
```
Rails 3.2.22
Ruby 1.9.3
Gems:
 * sidekiq-failures (0.4.3)
  * sidekiq-pro (1.5.1)
  * sidekiq (2.17.7)
  * sidekiq-status (0.5.0 84e2747)
  * sidetiq (0.6.1)
  * mysql2 (0.3.19)
```
You will note, of course, that we are running an older version of sidekiq because we are still on Ruby 1.9.3. An upgrade to Ruby 2.2.2 is in QA and is due to be released within the next 2 weeks.

Here is an example backtrace:
```
/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245 in query
/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245 in block in execute
/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_adapter.rb:280 in block in log
/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20 in instrument
/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_adapter.rb:275 in log
/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/active_record.rb:59 in block in log_with_newrelic_instrumentation
/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/method_tracer.rb:73 in block in trace_execution_scoped
/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/method_tracer_helpers.rb:82 in trace_execution_scoped
/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/method_tracer.rb:71 in trace_execution_scoped
/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/active_record.rb:56 in log_with_newrelic_instrumentation
/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245 in execute
/gems/activerecord-3.2.22/lib/active_record/connection_adapters/mysql2_adapter.rb:213 in execute
/gems/activerecord-3.2.22/lib/active_record/connection_adapters/mysql2_adapter.rb:217 in exec_query
/gems/activerecord-3.2.22/lib/active_record/connection_adapters/mysql2_adapter.rb:226 in select
/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/database_statements.rb:18 in select_all
/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/query_cache.rb:63 in select_all
/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/database_statements.rb:24 in select_one
/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/database_statements.rb:30 in select_value
/gems/activerecord-3.2.22/lib/active_record/relation/calculations.rb:250 in execute_simple_calculation
/gems/activerecord-3.2.22/lib/active_record/relation/calculations.rb:215 in perform_calculation
/gems/activerecord-3.2.22/lib/active_record/relation/calculations.rb:159 in calculate
/gems/activerecord-3.2.22/lib/active_record/relation/calculations.rb:58 in count
app/models/gradebook/stale_assignments.rb:13 in stale_assignments_count
app/models/gradebook/stale_assignments.rb:8 in any_stale_assignments?
app/models/gradebook/updater.rb:42 in make_section_current
app/models/gradebook/updater.rb:28 in block in make_all_courses_current
/gems/activerecord-3.2.22/lib/active_record/relation/batches.rb:21 in block (2 levels) in find_each
/gems/activerecord-3.2.22/lib/active_record/relation/batches.rb:21 in each
/gems/activerecord-3.2.22/lib/active_record/relation/batches.rb:21 in block in find_each
/gems/activerecord-3.2.22/lib/active_record/relation/batches.rb:72 in find_in_batches
/gems/activerecord-3.2.22/lib/active_record/relation/batches.rb:20 in find_each
app/models/gradebook/updater.rb:27 in make_all_courses_current
app/workers/gradebook_updater_worker.rb:13 in block in perform
app/workers/worker_instrumentation.rb:6 in time_and_log
app/workers/gradebook_updater_worker.rb:13 in perform
/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:49 in block (3 levels) in process
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:122 in call
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:122 in block in invoke
/gems/statsd-ruby-1.2.1/lib/statsd.rb:232 in time
lib/patches/sidekiq/middleware/server/statsd.rb:33 in call
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124 in block in invoke
lib/sidekiq/persistence/server_middleware.rb:12 in call
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124 in block in invoke
[GEM_ROOT]/bundler/gems/sidekiq-status-84e2747a9b10/lib/sidekiq-status/server_middleware.rb:37 in call
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124 in block in invoke
/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/sidekiq.rb:33 in block in call
/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:361 in perform_action_with_newrelic_trace
/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/sidekiq.rb:29 in call
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124 in block in invoke
/gems/sidetiq-0.6.1/lib/sidetiq/middleware/history.rb:17 in call_with_sidetiq_history
/gems/sidetiq-0.6.1/lib/sidetiq/middleware/history.rb:6 in call
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124 in block in invoke
/gems/sidekiq-pro-1.5.1/lib/sidekiq/batch/middleware.rb:26 in call
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124 in block in invoke
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/active_record.rb:6 in call
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124 in block in invoke
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/retry_jobs.rb:62 in call
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124 in block in invoke
/gems/sidekiq-failures-0.4.3/lib/sidekiq/failures/middleware.rb:9 in call
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124 in block in invoke
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/logging.rb:11 in block in call
/gems/sidekiq-2.17.7/lib/sidekiq/logging.rb:22 in with_context
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/logging.rb:7 in call
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124 in block in invoke
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:127 in call
/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:127 in invoke
/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:48 in block (2 levels) in process
/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:108 in stats
/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:47 in block in process
/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25 in call
/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25 in public_send
/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25 in dispatch
/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67 in dispatch
/gems/celluloid-0.15.2/lib/celluloid/future.rb:14 in block in new
/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13 in block in initialize
/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100 in call
/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100 in block in create
```

**Comment by mperham** [comment] 2015-08-20 19:23
Looks like a dupe of #1945, bug is being tracked in brianmario/mysql2#547.

**Closed by mperham** 2015-08-20 19:23 UTC
