### ISSUE TITLE
`status.complete?` overall batch never returns true, even if children are `complete?`

### ISSUE THREAD

**Issue by srpouyet** [mperham/sidekiq#3519] opened 2017-06-16 20:19 UTC
Hi Mike or colleague,

I'm implementing a Sidekiq Pro batch using [Really Complex Workflows with Batches](https://github.com/mperham/sidekiq/wiki/Really-Complex-Workflows-with-Batches) as a starting point. At the moment this has got me stumped: `status.complete?` of the "overall" batch never returns `true`, even though its child batches do. 

You can find a testcase in this [gist](https://gist.github.com/srpouyet/68b634626d61c4539bf0e6c1de734169).

The only strange thing I noticed is that one job seems to be deleted:

```
=> #<Sidekiq::Batch::Status:0x007f95c7fc58a0
 @bid="A5IBIDKKBY0pew",
 @completed=0,
 @failures=0,
 @pending=0,
 @props=
  {"kids"=>"3",
   "created_at"=>"1497539062.073876",
   "description"=>"Overall batch",
   "total"=>"1",
   "deleted"=>"1",
   "pending"=>"0",
   "callbacks"=>"{\"complete\":[{\"WorkFlowCallbacks\":{}}],\"success\":[{\"WorkFlowCallbacks\":{}}]}"}
```

Have I missed something, is this expected behaviour or is something amiss?

Tested with ruby 2.3.1p112, sidekiq 4.2.10, sidekiq-pro 3.4.5, Redis 3.2.9, Rails 4.2.8

Sidekiq initializer:
```
Sidekiq.configure_server do |config|
	# TODO: Use unix socket instead of TCP with { path: "/var/run/redis/redis.sock", db: 12, namespace: "#{Rails.env}:sidekiq" } option.
	if Rails.env.production? || Rails.env.demo?
		config.redis = { url: ENV['REDIS_WORKER_URL'] }
	else
		config.redis = { url: ENV['REDIS_WORKER_URL'], namespace: ":#{Rails.env}:sidekiq" }
	end
end


Sidekiq.configure_client do |config|
	if Rails.env.production? || Rails.env.demo?
		config.redis = { url: ENV['REDIS_WORKER_URL'] }
	else
		config.redis = { url: ENV['REDIS_WORKER_URL'], namespace: ":#{Rails.env}:sidekiq" }
	end
end

Sidekiq.default_worker_options = { 'backtrace' => true }

# Perform Sidekiq jobs immediately in development,
# so you don't have to run a separate process.
# You'll also benefit from code reloading.
# if Rails.env.development?
# 	require 'sidekiq/testing'
# 	Sidekiq::Testing.inline!
# end
```

Thank you for looking into this!

**Comment by mperham** [comment] 2017-06-16 20:53
`deleted` isn't a counter in this case, it's a flag meaning the batch was successful and will be deleted from Redis shortly.

The issue is that once a batch is deleted, it's running state data is also deleted.  This meant the `Status#complete?` method erroneously thought the batch was still incomplete.  That's a bug and will be fixed in the next release.

Your overall workflow's complete callback was fired early because all jobs had completed and all children had completed.  This is expected behavior.

https://gist.github.com/srpouyet/68b634626d61c4539bf0e6c1de734169#file-sidekiq_test_log-txt-L10

The overall workflow's success callback was not fired early because the child batch's success callback added more jobs.  This is expected behavior.

**Comment by srpouyet** [comment] 2017-06-17 07:01
Aha, that explains it. As a workaround I'll just check for the `deleted` flag. Thanks for your quick reply and picking it up for the next release. 👍

**Closed** 2017-06-21 20:11 UTC
