### ISSUE TITLE
Sidekiq Crypto doesn't work with inline tests

### ISSUE THREAD

**Issue by lojack** [mperham/sidekiq#3357] opened 2017-02-15 17:13 UTC
Ruby version: 2.3.3p222
Sidekiq / Pro / Enterprise version(s): 4.2.9 / 3.4.3 / 1.5.1

I've implemented Sidekiq::Enterprise::Crypto functionality, and it works fine in development environments, but I have a number of integration tests that fail because the middleware isn't being included. 

This happens when I have a test that does something like:

```ruby
 Sidekiq::Testing.inline! do
   expect { worker.perform }.to change { ExampleModel.count }
 end
```

For these test cases, the parameter is being encrypted, but never gets decrypted because the `Sidekiq::Enterprise::Crypto::Server` middleware is never included. I'm able to work around this by manually including the middleware.

**Comment by mperham** [comment] 2017-02-15 17:18
Dupe of https://github.com/mperham/sidekiq/issues/3208

**Closed by mperham** 2017-02-15 17:18 UTC
