### ISSUE TITLE
Sidekiq + Activejob emails aren't sent with deliver_later in production.

### ISSUE THREAD

**Issue by abeltje1** [mperham/sidekiq#3965] opened 2018-09-14 14:49 UTC
```
Ruby version: 2.4.0
Sidekiq  version(s): 5.1.3
Rails version: 5.1.6
```

Please include your initializer and any error message with the full backtrace.

```
require 'sidekiq/web'
Sidekiq::Web.set :sessions, false
Sidekiq.default_worker_options = {backtrace: true}
```

Are you using an old version? Yes 
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes and it doesn't look like it

Dear all,
First of all I'd like to say I love working with Sidekiq in general - it's fast and reliable, with an impressive UI (for an OS project!), but I'm experiencing one issue and after hours of searching, I decided to post here:

When I try to send e-mails with Sidekiq (5.1.3) and Rails (5.1.6) in production using ActiveJob's deliver_later, e-mails are not being sent (deliver_now works fine). The job gets processed and Sidekiq reports it as such; the logs show no errors whatsoever. The logs show a successful start & done:

`2018-09-14T14:12:18.031Z 14029 TID-mncgx ActionMailer::DeliveryJob JID-665575b056e61ef84a434c97 INFO: done: 0.84 sec
`
The only thing missing is the delivery of the actual e-mail. I've enabled 'raise_delivery_errors', but nothing is being raised. I'm sending my email through Mailgun.
I'm inclined to think something's going wrong with Sidekiq, because I had ActiveJob configured before (with the default adapter, :async) and deliver_later worked properly. Only after adding Sidekiq it stopped working. I've tried it with many different e-mails and in the end I created an extremely simple mailer, just for debugging this issue. I also must note that it does work properly in development, but not in production. Does anyone have an idea what could be the cause of this & how I could research it? 

```
class SimpleMailer < ApplicationMailer

  # Subject can be set in your I18n file at config/locales/en.yml
  # with the following lookup:
  #
  #   en.simple_mailer.test.subject
  #
  def test
    @greeting = "Hi"
    mail to: xx, from: xx, subject: 'Well hello"
  end
```

Thanks a lot in advance! I've been searching for quite some time now and have lost almost all inspiration - any help (on where to look) would be amazing. I could also provide more info, but I don't really know what's more to provide. Let me know!

**Comment by mperham** [comment] 2018-09-14 16:12
No clue what might be wrong.

**Comment by abeltje1** [comment] 2018-09-14 19:03
Any idea on what'd be the best strategy for digging deeper into the issue?

**Comment by mperham** [comment] 2018-09-14 19:32
Turn on all Rails, mail and actionmailer debugging.

**Comment by abeltje1** [comment] 2018-09-15 09:58
I've tried swapping sidekiq with resque & with delayed_job and both send e-mail just fine in production with deliver_later. This really leads me to believe the issue is with Sidekiq (right?). Because my team has limited time, I think we'll be switching to resque (even though we prefer sidekiq for all things aside this bug) sadly enough. For a last try: do you have any idea why these other frameworks do work and sidekiq doesn't?. It;d be really neat if we could use Sidekiq!

**Comment by mperham** [comment] 2018-09-15 22:16
1000s of people use Sidekiq to deliver emails in production every day.  The problem is in your app code.  You can switch to another system but you are only moving to a slower, less capable system because you can't debug your own app.  Give me an app that can reproduce the problem and I can help debug but I guarantee the problem is not in Sidekiq itself but rather your configuration of the whole application.

**Closed by mperham** 2018-09-15 22:16 UTC
